command.go, command_test.go
@jlowdermilk @spf13 @smarterclayton ptal.
Thanks!
--brendan
=> Add mergePersistentFlags in strip flags since we now look at the flag set.

cobra.go, command.go
=> Add mousetrap for Windows users

README.md
=> Fix misspelling typo

README.md, cobra_test.go, command.go
This rebases #53, adds docs, and adds tests.
=> Pre post run fucntions

command.go
The template had gotten out of control. It was basically unparsable.
This does a little more work in functions and a little less in the
template. Overall it should be basically the same. It might output the
'additional help topics' in a couple of fewer places, but I doubt people
complain too much...
I'm just not sure about this part of the old template:
```
{{if .HasRunnableSiblings }}{{range .Parent.Commands}}{{if and (not .Runnable) (not .Deprecated)}}{{if not (eq .Name $cmd.Name) }}
```
It looks to like it only happens if you have a runnable sibling but then it tells you about your non-runnable siblings? Huh? Whatever was done, it wasn't right....
=> Update help template

man_docs.go
=> turn generated man pages non k8s specific.

command.go
This is in reference to issue #67 and creates all the E functions and adds them to execute. Use @eparis patch as the std point of reference.
=> #67 creates RunE functions to allow for errors to populate to the top

command.go
=> Added documentation for ArgsLenAtDash

cobra_test.go, command.go
This should address and fix #191
=> Creates the ExecuteC function while maintaining Execute signature

bash_completions.go
Also adds support for generating bash completions on writers other than
just buffers.
Found via github.com/mvdan/interfacer.
=> Replace *bytes.Buffer with io.Writer

doc/man_docs.go, doc/man_docs.md, doc/md_docs.go, doc/md_docs.md
=> Fix doc generation and its documentation

cobra/cmd/init.go
=> Update template per to match previous pr with golint fix

command.go
Fixes https://github.com/spf13/cobra/issues/307
@eparis PTAL
=> Restore Help() and Usage() for backwards compatibility

.travis.yml, bash_completions_test.go, cobra_test.go, command_test.go, doc/man_docs.go
Also small cleanup to cobra_test.
=> gofmt, govet, run those in Travis

bash_completions.go, cobra.go, command.go
Made some fixes according to `gometalinter`
=> Some fixes

command.go
I think, it's more obvious now, what does this method
=> Fix condition in HelpFunc

cobra_test.go
echo msg not echo msg msg in Test Function "func TestSubcommandExecuteC(t *testing.T) {......}"
=> echo msg not echo msg msg

README.md
fmt package should be imported in this code block
Signed-off-by: Qinglan Peng <qinglanpeng@zju.edu.cn>
=> fmt package should be imported

bash_completions.go, cobra.go, command.go
Added/modifed godocs to the public methods to make `golint` happy.
=> Added godocs to public methods.

command.go
=> Some fixes related to help command

command.go, doc/man_docs.go, doc/md_docs.go, doc/util.go, doc/yaml_docs.go
Fixes #393
Created this PR just to end the discussion of #393
=> Rename IsHelpCommand to IsAdditionalHelpTopicCommand

bash_completions.go, command.go, command_test.go
Please see commit messages. @spf13 
cc @spencerkimball
=> Avoid storing pointer to nil

command.go
=> Keep only one newline between Aliases and Flags in help

command.go
=> Get rid of flagErrorBuf

cobra/cmd/init.go, cobra/cmd/root.go
=> Use os.Getenv("HOME") instead of "$HOME" for windows compatibility

README.md, cobra/cmd/helpers.go, cobra/cmd/helpers_test.go, cobra/cmd/license_agpl.go, cobra/cmd/license_gpl_2.go, cobra/cmd/license_gpl_3.go, cobra/cmd/license_lgpl.go, cobra/cmd/licenses.go
Fixes #311
Fixes #318 
Fixes #322
Closes #356
/cc @MarkDBlackwell @eparis @spf13
=> cmd: Fix license issues

cobra_test.go, command.go, command_test.go
=> Initialize help flag in initHelpCmd

cobra/cmd/license_agpl.go, cobra/cmd/license_gpl_2.go, cobra/cmd/license_gpl_3.go, cobra/cmd/license_lgpl.go
Notes from https://github.com/spf13/cobra/pull/418#discussion_r113724661.
Huge thanks @pombredanne for help and remarks.
/cc @pombredanne
=> cmd: Licenses refactoring

command.go, command_test.go
Useful for solving #424
/cc @spf13 @eparis @bep
=> Make initHelpFlag public

bash_completions.go, bash_completions_test.go
Use buf instead of writing directly to w.
Improve test coverage from 80% to 85%.
=> Simplify bash_completions.go

README.md
see https://github.com/spf13/cobra/issues/450
=> Edits installation command

command.go
Useful for solving #424
/cc @spf13 @eparis @bep
=> Make initHelpCmd public

README.md
=> Add explanation for viper.BindPFlag in README.md

cobra/cmd/add.go, cobra/cmd/root.go
=> cmd: Add possibility to specify the target package

command.go, command_test.go
Fix #463 
/cc @kashishm @eparis
=> Show message if deprecated flags are used

README.md
I considered phrasing it `you will experience unexpected errors`. Encounter implies an unexpected meeting.
=> Reword `become unexpected errors` to `encounter errors`

README.md
`rootCmd` should be `RootCmd`.
=> Fix RootCmd var name

cobra.go, command_win.go
Fix #486
Close #383 (no progress there)
=> Add ability to disable mousetrap

cobra/cmd/add_test.go, cobra/cmd/init_test.go, cobra/cmd/licenses.go
=> cmd: Fix golden tests if user has config at $HOME

README.md, command.go
* Add more examples of Args
* Retab README.md
/cc @eparis @dnephin @notjames
=> Improve documentation

zsh_completions.go
replicating the GenBashCompletion function from bash_completions.go
This will allow the completions to be generated in a consistent manner.
=> adding a GenZshCompletionFile function to mirror bash_completion

bash_completions.go, zsh_completions.go
It makes the docs looks better. The idea was suggested by @SamWhited
=> Use func (c *Command) consistently

cobra_test.go, command.go
=> Proposed fix for issue #521

README.md, cobra/README.md
=> Shorten README

cobra/README.md
Just added a comma. Read weird without it
=> Grammar addition

command.go, command_test.go
Currently when we set/mark a flag as required, `cobra` will not raise an error if unset.
This PR does enforce checking the required flags.
/cc @eparis
=> enforce required flags

command.go
Discussion: https://github.com/spf13/cobra/pull/422#discussion_r143918343
/cc @dixudx @eparis
=> Delete name field from Command

command_test.go
Discussion: [#547 (comment)](https://github.com/spf13/cobra/pull/547#issuecomment-335825065)
/cc @bogem @eparis
=> add test for deprecate alias and c.Name()

doc/md_docs.go
Signed-off-by: Allen Sun <shlallen1990@gmail.com>
=> test: remove one additional blank line after Synopsis

doc/md_docs.go
Signed-off-by: Allen Sun <shlallen1990@gmail.com>
=> test: add a necessary blank line after SEE ALSO

README.md, bash_completions.go
Was looking for this feature and came across #502, thought an example in the readme would be helpful
=> Add usage example for required flags

.circleci/config.yml, bash_completions.go
This is the second part of PR #588 
this will fix https://github.com/kubernetes/helm/issues/3171
=> support completions for command aliases

doc/man_docs.go, doc/man_docs_test.go, doc/md_docs.go, doc/md_docs_test.go, doc/rest_docs.go, doc/rest_docs_test.go
=> doc: hide hidden parent flags

bash_completions.md
Description doesn't match the actual code example
=> Fixed code sample for bash completion

bash_completions.md
#465 Obsolete bash completion example (kubernetes)... and use a better example anyway
=> Include a basic example #465

README.md
Signed-off-by: Federico <federico@imaginecurve.com>
=> #716 - Removed useless libraries in readme

cobra/cmd/add.go
Ref https://github.com/spf13/cobra/pull/673#issuecomment-511062820
=> fix missing newline in cmd/add

cobra/README.md
Update Generator Docs to reflect changes brought in #817 
Covers PRs:
#878
#888
=> update generator docs

cobra/cmd/testdata/main.go.golden, cobra/cmd/testdata/root.go.golden, cobra/cmd/testdata/test.go.golden
@umarcor 
Here is a separate PR for the year bump.
=> Bump year on golden files

command.go
Documentation on function is incorrect
=> Correct documentation for InOrStdin

projects_using_cobra.md
Helm has been using Cobra for years.
=> Add Helm as project using Cobra

projects_using_cobra.md
We appreciate your library and want thank by pointing to our usage.
=> Metal Stack CLI is using cobra as well

go.mod, go.sum
Upgrade to yaml.v2 v2.3.0 to fix vulnerability reported here - https://github.com/kubernetes/kubernetes/issues/89535
=> Closes #1152 by upgrading yaml.v2 to v2.3.0

projects_using_cobra.md
Add golangci-lint in project using cobra
=> Add golangci-lint in project using cobra

command.go
=> Add documentation for Use

doc/md_docs.go, doc/md_docs_test.go
=> Add the ability to specify a filePostpender in GenMarkdownTreeCustom

projects_using_cobra.md
Just announced! 🎉 
The `tanzu` CLI heavily uses the cobra library - ref: https://github.com/vmware-tanzu/community-edition
=> Update `projects_using_cobra` markdown with VMware Tanzu

cobra/tpl/main.go
=> fix: Duplicate error message from cobra init boilerplates

cobra/cmd/testdata/root.go.golden
It seems that merging #1463 broke CI. This PR hopefully fixes it.
/cc @jpmcb
=> fix root.go.golden

.github/labeler.yml
=> labeler: fix syntax

projects_using_cobra.md
Hi 👋 
We are using Cobra so thought to add our project here for people's reference. We used to learn a lot from the examples here so thought to share back.
=> doc: Add CloudQuery for projects using Cobra

projects_using_cobra.md
Signed-off-by: Javier López Barba <javier@okteto.com>
=> doc: Add Okteto for projects using Cobra

projects_using_cobra.md
Hi there 
I would love to add ZITADEL to the list of projects who are using cobra and viper as well 😁 
Thank you for this project!
=> docs: add zitadel to the list

powershell_completions.go
=> Force ForEach-Object to return array in pwsh completion

README.md
https://github.com/badges/shields/issues/8671
and fixed typo (tru -> true)
=> Update badge route

doc/man_docs_test.go
=> doc: fix typo, Deperecated -> Deprecated

command_test.go
I made minor modifications to some unit tests.
=> minor corrections to unit tests

site/content/projects_using_cobra.md
Update projects using Cobra markdown file
=> [chore]: update projects using cobra

.github/workflows/test.yml
Based temporary on #2181 for testing.
=> Test also with go 1.23
