cobra_test.go, command.go
When an unknown command is called on a non-runnable root, the error message stated twice, in slightly different ways:
```
~/code/src/github.com/adammck/cobra-test$ ./cobra-test whatever
Error: unknown command "whatever"
Run 'help' for usage.
cobra-test: invalid command [`whatever`]
Run 'cobra-test help' for usage
```
Neither of these are especially clear, so I merged them. The result is:
```
~/code/src/github.com/adammck/cobra-test$ ./cobra-test whatever
Error: unknown command "whatever"                        
Run 'cobra-test help' for usage
```
I believe this solves #29, and obsoletes #34.
=> Fix redundant error for unknown root commands

cobra_test.go, command.go
The special case code to handle a runnable root command had some
problems.  It was noticed that if you created a runnable root and a
subcommand.  And the subcommand was then executed with both a valid and
invalid flag, the error message was about the valid flag being invalid.
For example
./command subcommand --goodflag=10 --badflag=10
Would fail and tell you that --goodflag was an invalid flag. Instead if
we just do away with the special Command.execute() for the root command
the parser for subcommand is what prints the error and it gets it
right...
=> Stop special casing runnable root commands

command.go
This gets us to https://github.com/spf13/cobra/pull/41
There are some minor differences.....
#41 used  {{rpad .Use .UsagePadding }} {{.Short}}
We use:   {{rpad .CommandPath .CommandPathPadding}} {{.Short}}
#41 did not print sibling runnable command information
we do print sibling runnable command information
I'm happy to alter either...
=> Additional help topics

command.go
I wrote https://github.com/eparis/readable-golang-template which
converts golang templates into something structured around the
conditionals.  Obviously you can't just USE the output, but you can SEE
the problems.  In this case the output shows something like:
```
{{if .HasParent}}
{{if and (gt .Commands 0) (gt .Parent.Commands 1) }}
Additional help topics:
{{if gt .Commands 0 }}
{{range .Commands}}
{{if not .Runnable}}
{{rpad .CommandPath .CommandPathPadding}} {{.Short}}
{{end}}
{{end}}
{{end}}
{{if gt .Parent.Commands 1 }}
{{range .Parent.Commands}}
{{if .Runnable}}
{{if not (eq .Name $cmd.Name) }}
{{end}}
{{rpad .CommandPath .CommandPathPadding}} {{.Short}}
{{end}}
{{end}}
{{end}}
{{end}}
{{end}}
```
We have a completely unused "{{if not (eq .Name $cmd.Name) }}"
Move the {{end}} after …
=> fix usage template conditional

README.md, cobra_test.go, command.go
This method removes children commands of an existing command.
This allows to build CLI clients that can be extended by 3rd party tools, by adding some commands and removing/replacing some others. For instance to replace the “version” command.
Note: For now the 1st defined command is executed, so it is not possible to override an existing command.
But anyway, deleting an old command then adding a new one is the ultimate way to be certain there is no confusion.
=> Add Command's RemoveCommand method

README.md, bash_completions.go, bash_completions.md, bash_completions_test.go, command.go
That's right.  A golang program the writes a bash program!
=> Bash Autocompletion Generator

bash_completions.go
We do this so we get stable repeatable output and can see if updates are
necessary or if it is just golang doing the same thing twice differently
=> Sort the valid args before output

cobra_test.go, command.go
running a command like: 
```
openshift admin policy add-role-to-user admin my-user
```
where `admin` and `my-user` are arguments to the `openshift admin policy add-role-to-user` command, removes the `admin` argument (`args[4]`).
This pull stops removing more than one token from the `args` for command matches.
@smarterclayton Related to https://github.com/openshift/origin/issues/1894
=> prevent removal of valid arguments

md_docs_test.go
We were printing the markdown, don't ask me why.
=> quiet down to go test for markdown generation

command.go
Some projects pick up flags from other projects they include.  A great
example would be projects that use glog and thus get all of those flags.
Kubernetes, for example, merges those flags manually into its commands.
This was reported in https://github.com/spf13/cobra/issues/44
What this patch does is merge those flags into the PersistentFlags on
the highest parent.  This allows kubernetes to stop having to merge
things themselves...
=> Make flags declared outside spf13.pflag persistent flags on the parent

bash_completions.go, bash_completions_test.go, cobra_test.go, command.go, md_docs.go, md_docs_test.go
They should still work, but shouldn't show up in help or usage output
=> Deprecated subcommands

cobra_test.go, command.go
This is a fix for the following use case:
If I create a command A that is going to be a subcommand on B and then I add B as a subcommand to C (with this particular order on AddCommand), then A is not going to inherit PersistentPostRun and PersistenPreRun functions.
=> Fixed Persistent-Run function propagation

bash_completions.go, bash_completions_test.go
We were trying to call a bash function with bash stuff like @ () from a
variable.  Stop that.  Just call a function with an arg from a variable
instead of trying to pass around the bash.
Should fix https://github.com/spf13/cobra/pull/103
=> make filename extension handling a bash function

md_docs.go, md_docs.md
The automatic Markdown generator works great!
But to use it to render the documentation in Hugo, we need front matter and slightly different links.
This commit adds optional callback funcs to add that.
=> genmarkdown: add optional frontmatter- and linkadjustment-funcs

md_docs.go
Fix default behavior added by #109. It's not typical to prepend the full filepath in a generated file, especially as that path will differ between e.g. a dev's laptop and a ci environment.
=> Don't prepend filename in default GenMarkdownTree

bash_completions.go, bash_completions_test.go
Simplifies setting the annotation on a flag to drive file selection in the bash autocompletion
=> Simplify setting file/extension annotations on a flag

cobra_test.go, command.go
by now, if someone calls: `program --validflag unknowncommand` the
output will be:
```
Error: unknown command "--validflag"
Run 'program help' for usage.
```
This patch strips out flags so the unknown command is printed:
```
Error: unknown command "unknowncommand"
Run 'program help' for usage.
```
=> Correctly print the unknown command name

bash_completions.go, bash_completions_test.go
This first `cd` to a specified directory, then
lists the subdirectories therein with `_filedir -d`.
This can be used by e.g. `hugo --theme=[Tab][Tab]`, which would
give a list of subdirectories under the `themes` directory.
See Pull Request spf13/hugo#1343 for more information.
=> Add new BashCompSubdirsInDir annotation

cobra_test.go, command.go
```go
package main
import (
"github.com/spf13/cobra"
"github.com/spf13/pflag"
)
func main() {
cmd := &cobra.Command{
Use:   "min",
Short: "minimal command",
Run:   func(_ *cobra.Command, _ []string) {},
}
pflag.String("oncmdline", "oncmdline", "oncmdline")
cmd.Execute()
}
```
Is a minimal cobra program.  When --help is displayed without this patch you get no indication the "oncmdline" is a valid flag. But it does work. With the patch --oncmdline is shows under flags.
=> Display pflag.CommandLine flags as if they were declared on the parent

command.go
This should let users overwrite it with something custom. Like the help
sub-command.
=> Initialize the --help flag as late as possible

cobra.go, cobra_test.go
This patch enables developers to add one to many template functions that
can be used by custom Usage and Help templates. Here is an example that
is included in the file cobra_test.go as the test function named
TestAddTemplateFunctions:
AddTemplateFunc("t", func() bool { return true })
AddTemplateFuncs(template.FuncMap{
"f": func() bool { return false },
"h": func() string { return "Hello," },
"w": func() string { return "world." }})
const usage = "Hello, world."
c := &Command{}
c.SetUsageTemplate(`{{if t}}{{h}}{{end}}{{if f}}{{h}}{{end}} {{w}}`)
if us := c.UsageString(); us != usage {
t.Errorf("c.UsageString() != \"%s\", is \"%s\"", usage, us)
}
In the above example four functions are added to the template function
map used when the Usage and Help text is generated from the templates
that …
=> Template Function Injection

command.go
Without this, RunE commands show up incorrectly in usage output.
=> RunE commands should be considered runnable.

bash_completions.go
If they installed bash-completions from homebrew, this should make our
completions work.
=> Enable bash completions on Macs

command.go
This trims some whitespace from the built-in templates.
In https://github.com/cockroachdb/cockroach, we have a test that asserts on the output of our CLI commands. This change makes it easier to write that test case when using a whitespace-trimming editor.
=> trim trailing whitespace

command.go
Before --help would start
```
Usage:
command [flags]
[...]
```
After --help will show
```
Usage:
command [flags]
[...]
```
=> No leading newline if Short and Long both unset

cobra.go, command.go
The flags usage template from pflags has a trailing \n. We need to
include a newline in case there are no flags in our template. This will
trim the newline from the end of the flags from pflag and we can do it
right outselves.
=> No newline after Flags in usage

README.md, cobra.go, cobra_test.go, command.go
Adds *optional* support to suggestions when "unknown command" errors happen. This allows Cobra to mimic the behaviour of `git`, like in:
```
$ git fethc
git: 'fethc' is not a git command. See 'git --help'.
Did you mean this?
fetch
```
=> Allows command suggestions along with "unknown command" errors

cobra_test.go, command.go
This allows a program to know what args came before the -- and what args
came after.
=> Provide the length of Args when a -- is found in commandline

README.md, cobra_test.go, command.go
Multiple improvements to suggestions when "unknown command" errors happen. Basically a `HasPrefix` will now also match, and adds the `SuggestFor` attribute to allow explicit suggestions. By setting that attribute you can for example suggest the valid command `remove` when users try `delete`, if for some reason you don't want actual aliases.
=> Improve suggestions

cobra_test.go, command.go
In waiting for #168, I kinda need this bug fixed so I took most of what @bep did but made it configurable as suggested by @spf13 and @eparis. This should fix #162.
=> [silence-errors]: adds a way for errors to silenced down the stack

cobra_test.go, command.go
Reverse a swap in logic introduced in #169 that would cause the usage
output to be printed twice.
Fixes #171
=> Ensure the usage command is printed only once

bash_completions.go
OSX has an older version of bash. So it doesn't have compopt.
=> Modifying bash completions so they can run on OSX

command.go
This should fix the tests by checking if first arg is the same as the name as the root command in cobra. Replaces PR #155 @eparis @spf13 @anthonyfok
=> fixes verbose tests by checking if the first arg belongs to cobra

bash_completions.go, bash_completions_test.go, cobra_test.go
This makes completions work with commands that have a colon in the name.  The issue came up when using [cmdns](https://github.com/gosuri/cmdns), but probably isn't limited to cases where this is used.
=> Bash completion for names with ':' character.

cobra.go, command.go, command_notwin.go, command_win.go
* Create command_win.go and command_notwin.go for windows only code
* Move call to mousetrap hook into separate preExecHook() function
=> Issue #195: Compile mousetrap only on Windows

bash_completions.go
If the `compspec` generates no matches it should use bash file name completion instead.
=> Use readline's default filename completion if completion fails

cobra.go, cobra_test.go, command.go
The commander must not infer that every command wants `[flags]` appended at the end of the usage string - some commands actually can't take flags there, for example something like:
```
rsh [flags] host -- REMOTE_COMMAND
```
This PR makes `[flags]` to only be added if it's not yet in the body of the usage string.
=> Must only add "[flags]" to the end of usage if not yet present

bash_completions.go, bash_completions.md, bash_completions_test.go
- add completion after `--flag=` or `--flag=abc`
- add flag annotation for custom flag completion, like e.g. for `--namespace=` in Kubernetes kubectl
=> Advanced custom bash completion of flags

README.md
This address part of #225 with adding information about `SilenceErrors` and `SilenceUsage`.
=> updates readme to Explain SilenceErrors and SilenceUsage #225

cobra/cmd/root.go
Fix the name in the comment to fix a golint bug by not having the variable name begin the comment.
=> Update root.go to fix golint bug with comment

bash_completions_test.go, cobra.go, cobra/cmd/helpers.go, cobra/cmd/root.go, cobra_test.go, command.go, command_notwin.go, doc/man_docs_test.go
* Moving final return outside of if-else
* Removing type declarations that Go can infer from values
* Cleaning up some existing comments
* Changing snake_case variables to camelCase
* Declaring slices using var instead of make
* Removing unused `err`
* Small gofmt change
=> Fixing golint warnings

bash_completions.go, bash_completions.md, bash_completions_test.go, command.go
Example:
- "rc" for replicationcontroller
- "pods" for "pod".
=> Add noun aliases

command.go
small error in function description.
[ci skip]
=> Fixed Small Comment Typo

.gitignore, bash_completions.go, command.go
If a user specified a non-persistent flag to a command they cannot then call a subcommand. Thus we should not display subcommands in the bash completions.
This also changes things such that we show both 'required flags' and 'subcommands' if a 'required flag' exists. Since you may be able to run a subcommand instead of use the 'required' flag.
=> Do not display bash commands if local flag specified

cobra.go, command.go, command_test.go
When the number of commands is big, help message become unreadable (It is hard to read "Available Commands" section and find proper command).
Example of output from Kubernetes project(`kubectl --help`):
```
Available Commands:
get            Display one or many resources
set            Set specific features on objects
describe       Show details of a specific resource or group of resources
create         Create a resource by filename or stdin
replace        Replace a resource by filename or stdin.
patch          Update field(s) of a resource using strategic merge patch.
delete         Delete resources by filenames, stdin, resources and names, or by resources and label selector.
edit           Edit a resource on the server
apply          Apply a configuration to a resource by filename or …
```
=> Sort commands by their names

doc/man_docs.go, doc/man_docs_test.go
* use `Command.UseLine()` instead of `Command.Name()` to get the correct args and usages string in the `SYNOPSIS`
* fixes a bug where a flags shorthand was being displayed even when it was deprecated
* fixed a bug where the man page section from the header was not being used as part of the filename (section 1 was assumed)
* add a new `GenManTreeFromOpts()` which takes additional options while leaving `GenManTree()` backwards compatible. Currently only takes one additional option, but it can be expanded without breaking backwards compatibility.
=> Fix man page gen bugs

cobra_test.go, command.go
Help when called from `-h` or the `help` command must print to Stdout. Right now it only happens in the root cmd, any subcommand (e.g. `cmd subcmd -h`) prints to Stderr.
Other minor code reorg.
=> Help command must use Stdout instead of Stderr

cobra_test.go, command.go
=> Fixes how we expose help and usage and expose output without making assumptions

README.md
This change added a few lines to the README.md documentation for building the cobra tool.
I spent a whole hour just to figure this thing out. I thought this is only available on Linux, so I get myself a Linux VM, and still, it does not work. Finally, I figured out the tool source code come with the library as a whole and I need to compile it in order to get it.
Writing this so that other don't have to follow the same path I did.
By the way, the document about how the commands are arranged in a tree is awesome.
=> Include instruction for building the cobra tool in README.md

bash_completions.go, bash_completions_test.go
As per the title.
I'm not certain if there's a reason not to hide both of these, but I'm open to opinions or discussion otherwise. Subcommands that are deprecated/hidden are already hidden it looks like.
=> Display neither hidden nor deprecated flags in bash completion

command.go, command_test.go, doc/md_docs.md
The default pflag error message only prints the bad flag. This enables an application to include a usage message or other details about the error.
I tried to match the design of the existing options (`UsageFunc` and `HelpFunc`).
=> Add support for setting a function to handle flag parsing errors

command.go, command_test.go
Small bug fix. Without this change calling `UsageFlags()` in the `Run()` of a command that doesn't have any other flags would use the wrong `help` flag, if  a custom help flag was set as a PersistentFlag() on a parent command.
=> Merge persistent flags before checking for a help flag

doc/man_docs.go
=> Make SEE ALSO references and generated file names agree with each other.

doc/util.go, doc/yaml_docs.go, doc/yaml_docs.md, doc/yaml_docs_test.go
Allow for Cobra to also generate YAML docs for the cli. 
Tests:
```
$ go test -v .
=== RUN   TestGenManDoc
--- PASS: TestGenManDoc (0.00s)
=== RUN   TestGenManNoGenTag
--- PASS: TestGenManNoGenTag (0.00s)
=== RUN   TestGenManSeeAlso
--- PASS: TestGenManSeeAlso (0.00s)
=== RUN   TestManPrintFlagsHidesShortDeperecated
--- PASS: TestManPrintFlagsHidesShortDeperecated (0.00s)
=== RUN   TestGenManTree
--- PASS: TestGenManTree (0.00s)
=== RUN   TestGenMdDoc
--- PASS: TestGenMdDoc (0.00s)
=== RUN   TestGenMdNoTag
--- PASS: TestGenMdNoTag (0.00s)
=== RUN   TestGenYamlDoc
--- PASS: TestGenYamlDoc (0.00s)
=== RUN   TestGenYamlNoTag
--- PASS: TestGenYamlNoTag (0.00s)
PASS
ok  	github.com/spf13/cobra/doc	0.015s
```
Output from the examples in `doc/yaml_docs.md`
test.go
```
$ cat /tmp/test.yaml …
```
=> Added support for yaml ouptut in docs gen

command.go
This `Tags` field would be used by an application to identify commands with specific properties. For example:
* experimental
* added-in version x
They could be used in custom help/usage text to group commands in different ways, or to filter the commands to hide based on tags.
See https://github.com/docker/docker/pull/28010 for a concrete use case.
cc @bep
=> Add a tags field for user defined tags on a Command

command.go
If one ran a command like
./root --boolFlag subcmd1 subcmd2
Thing worked fine. The code recognized that --boolFlag followed by a
space meant the next word was not the argument to --boolFlag. But other
flag types with a NoOptDefValue (like a Count flag) would not ignore the
"argument".  On a command like:
./root --countflag subcmd1 subcmd2
The processor, when looking for a subcommand, would first throw out the
`--countflag subcmd1` and then look for subcmd2 under root.
The fix is to ignore the next word after any NoOptDefVal flag, not just
boolean flags.
=> Fix subcommand locations with NoOptDefValue flags

README.md
You have to set them to true to silence the default output, not false.
=> Fix SilenceUsage and SilenceErrors in readme

README.md
Docker (https://github.com/docker/docker) now also uses Cobra for the CLI. A majority of the
commands have been migrated (still some left), but adding it already :)
=> Add "docker" to readme

command.go
This fixes an issue where each Execute call grows the number of times
`help` appears in the help command by 1.
=> remove help command before adding it

bash_completions.go
Fixed a bug when completing a dash argument ending with "=" will duplicate the parameter if there is nothing after the "=" character.
Example:
kubectl --log-dir=<tab>
would cause:
kubectl --log-dir=--log-dir=
=> Fixed completion of dash parameters arguments

README.md
Exit code value range is 0-255. I think the examples in the main README document should be valid both syntactically and semantically.
=> README: Use valid exit code value in `os.Exit` calls

cobra_test.go, command.go, command_test.go
I think It's more obvious now to understand the inheritance of flags.
Updates #395
Fix #403
Fix #404
Performance improvements:
```
benchmark                     old ns/op     new ns/op     delta
BenchmarkInheritedFlags-4     6536          5595          -14.40%
BenchmarkLocalFlags-4         3193          3235          +1.32%
benchmark                     old allocs     new allocs     delta
BenchmarkInheritedFlags-4     49             39             -20.41%
BenchmarkLocalFlags-4         23             21             -8.70%
benchmark                     old bytes     new bytes     delta
BenchmarkInheritedFlags-4     2040          1000          -50.98%
BenchmarkLocalFlags-4         1008          544           -46.03%
```
Also merge of https://github.com/spf13/pflag/pull/119 will significantly …
=> Refactor flags mechanisms

README.md
If the developer is missing any dependencies, for instance `github.com/spf13/cobra/cobra`, `go install` will fail:
```bash
../../spf13/viper/util.go:29:2: cannot find package "gopkg.in/yaml.v2" in any of:
/Users/campoy/src/golang.org/x/go/src/gopkg.in/yaml.v2 (from $GOROOT)
/Users/campoy/src/gopkg.in/yaml.v2 (from $GOPATH)
```
While `go get github.com/spf13/cobra/cobra` will build the tool successfully.
=> Use go get so missing dependencies are fetched

README.md
I've converted rclone over to use cobra - what a great package - thank you very much.
- http://rclone.org
- https://github.com/ncw/rclone
Here is a PR to add rclone to the list of users.  I don't know whether 2,000 github stars is popular enough for the list - if not please disregard this PR!
Thanks
Nick
=> Add rclone to list of users

command.go
=> Fix typo at docstring for HasHelpSubCommands

cobra.go, command.go
* Delete `Eq`, `Gt`, `appendIfNotPresent` and `trim` functions
* Add `[flags]` in UseLine
* Simplify other functions
* Simplify templates
⚠️   **Public API changes:** Delete public `Eq`, `Gt` functions.
*`Eq` is used nowhere, `Gt` was used only in template.* I looked in some projects that use cobra, and I found out, what (almost) no one uses them.
---
Minor performance improvement.
Benchmark for command with 4 flags and one child command:
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkCmdUsageFunc-4     335860        319290        -4.93%
benchmark                   old allocs     new allocs     delta
BenchmarkCmdUsageFunc-4     562            543            -3.38%
benchmark                   old bytes     new bytes     delta
BenchmarkCmdUsageFunc-4     21623 …
```
=> Improve template mechanisms

cobra.go
There were template functions which we defined and others started using.
Although we no longer want those functions, since others use them,
deleting them breaks our API.  Putting those (unused) functions back.
Fixes the report in https://github.com/spf13/cobra/pull/422#issuecomment-300263377
=> Partial revert of 4d2c4af 'Improve template mechanism'

bash_completions.md
"Plural form and shortcuts for nouns" section had a stray backtick, making Markdown rendering for code examples strange. Removed said backtick.
=> Updating bash_completions to clarify markdown

README.md
Cobra is not using that version of pflag, but a fork of it.
It's a minor issue, but I ran into a bunch of dependency hell issues because I accidentally updated that one instead of the fork while trying to update cobra in a project.
=> Update pflag link in README.

cobra_test.go, command.go
Consider these program:
```go
package main
import (
"fmt"
"os"
)
func main() {
for _, a := range os.Args {
fmt.Printf("%q ", a)
}
}
```
While executing it as `go run main.go -i="qwe" "qwe qwe" -i=qwe` we become `"/path/to/temp/binary" "-i=qwe" "qwe qwe" "-i=qwe"`. Args are not split with space, as it is in tests. So we don't need to manually quotes. It makes shell.
`spf13/pflag` and standard `flag` libs are processing flags this way too.
=> Fix tests so they give correct args

bash_completions.go
So bash-completion should check first
=> __ltrim_colon_completions is not always available on macOS

README.md
The function called `main` in the manual creation example should be called
`initConfig`.
=> Rename main func to initConfig

README.md
When `home` can't be determined it doesn't make sense to print it.
The value of `err` should be printed instead.
=> Print err instead of home

README.md, args.go, bash_completions_test.go, cobra_test.go, command.go
Fixes #42
Branched from #120
Adds a new field `Args` that allows a user to define the expected positional arguments that a command should receive. If a command doesn't receive the expected args it returns an error.
By accepting a validation function users can create their own custom validation for positional args. This PR includes validators for the most common cases.
=> Support validation of positional arguments

cobra_test.go
According to golang/go#9504 and https://golang.org/pkg/reflect/#Value,
== should not be used on two reflect.Values, but comparing the results
of their Interface() method does not work in this case, so let's
compare the results of their Pointer() method instead.
See https://stackoverflow.com/questions/9643205/how-do-i-compare-two-functions-for-pointer-equality-in-the-latest-go-weekly
=> Fix TestGlobalNormFuncPropagation() on gccgo

cobra/cmd/add_test.go, cobra/cmd/init_test.go, cobra/cmd/licenses.go
These tests were time-dependent and would start failing in 2018
when the golden files still have the copyright year of 2017.
Fix by hard-coding the year 2017 for the purpose of these two tests
to ensure reproducible builds.
Fixes #503
=> Fix reproducibility in TestGolden{Add,Init}Cmd

zsh_completions.go, zsh_completions_test.go
Support for flags still missing though. Maybe we can go from here.
=> Issue #107: add basic zsh completion (command hierarchy only)

cobra/cmd/helpers.go
Fixes #527.
This handles the default `$GOPATH` by checking if the environment variable exists, otherwise using the output of `go env GOPATH`. It is the same method as the Glide project (https://github.com/Masterminds/glide/pull/798/files).
This `init` script is the only place where the `GOPATH` environment variable is accessed, so this change should be sufficient for the project.
A questionable feature is the `COBRA_GO_EXECUTABLE` environment variable - I copied it from Glide, but it might not be needed.
=> Support default value of $GOPATH

README.md, command.go, command_test.go
Fixes #277
Currently cobra only parses flags on the last command in the chain. If you use `PersistentFlags()` you force the parent flag onto the child commands, cluttering help, and reducing the short flags available to child commands.
`TraverseChildren` allows each command in the hierarchy to have its own flags. Flags are parsed as commands are found during the `Traversal()`.
=> Add a TraverseChildren option to allow for flags on each command in the hierarchy

command.go, command_test.go
This PR fixes a nil dereference when `TraverseChildren` is used with multiple subcommands.
=> Fix TraverseChildren used with multiple subcommands

README.md
This part of the example is a bit confusing since you use `cmd.RootCmd.Execute()` everywhere, but never use this function.
=> Remove confusing duplicate Execute from README

command.go
`Command.UseLine()` will append a `[flags]` string for any command that has flags. This behaviour is often wrong. For example, in the following cases:
* the use line documents flags using some other string (`[FLAGS]`, `[OPTIONS]`, etc)
* the use line includes positional arguments, and https://godoc.org/github.com/spf13/pflag#SetInterspersed is set to false. This requires that flags appear before any positional arguments, so appending the string to the end of the use line is incorrect.
To fix these two problems I've added a new field to disable adding `[flags]` to the `UseLine`. The application will be responsible for included the string in the appropriate position in the usage line.
=> Add a field to disable [flags] in UseLine()

command.go, command_test.go
Make it so that first letter is not capitalized and rephrase
to remove "have/has".
=> Update error message for missing required flags

README.md
Alphabetize and separate builtin imports from external imports
to be gofmt-compliant and consistent with other examples in README.
=> Fix README example to be consistent with others

README.md, cobra/cmd/add.go, cobra/cmd/init.go, cobra/cmd/testdata/root.go.golden, cobra/cmd/testdata/test.go.golden
Update Cobra generator to make rootCmd private rather than
exporting it. Also update examples in README to use the exported
Execute() command rather than referencing unexported rootCmd.
Fixes #556
=> Make rootCmd private

command.go, command_test.go
=> Add support for --version flag

README.md
Signed-off-by: Allen Sun <shlallen1990@gmail.com>
What this PR did:
I try to add project [alibaba/pouch](https://github.com/alibaba/pouch) which is another container engine which has beed used widely in Alibaba in README.md of cobra. We have to say cobra plays an important role in Pouch. And we not only use cobra to implement cli code, but also use cobra to auto-generate cli documentation. We wish pouch could be a strong evidence that cobra could be help a lot.
=> doc: add alibaba/pouch in README.md

command.go, command_test.go
Make it so that, in the case that the root command is not runnable
but has subcommands, specifying a '--version' flag will still
run the "version" behavior.
=> Ensure that '--version' flag works properly for root command

cobra/cmd/init.go, cobra/cmd/testdata/root.go.golden
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> Remove trailing whitespace in rootcmd

cobra/cmd/helpers.go, cobra/cmd/project.go
If user has a project in symlink, just use its destination folder and
work there.
=> cmd: Fix #612

bash_completions.go
flaghash variable is an associative array which is only supported in bash > 3.
```
kubectl get service --namespace=kube-system k-bash: --namespace=: attempted assignment to non-variable (error token is "=")
```
fixes https://github.com/kubernetes/kubectl/issues/121, https://github.com/kubernetes/kubernetes/issues/29322, https://github.com/kubernetes/kubernetes/issues/32676
=> Fix attemptd assignment to non-variable in bash 3

command.go, command_test.go
The `CalledAs` method returns the name of the command or alias that
invoked the command -- as long as the command was actually invoked.
Otherwise, it returns the empty string.
The opens up possibilies for commands to behave differently based on
which alias invoked the command (in the same vein as Linux programs
which adjust their behavior based on the value of argv[0]).
=> Add `CalledAs` method to cobra.Command (w/ tests)

README.md
Hi,
I'm a golang rookie and had a hard time grasping where the `cmd.Execute()` function came from in the first Getting Started section of the `README.md`. Hopefully it helps other not spending unnecessary time connecting the dots 😄 
This trivial addition defines the `cmd.Execute()` function that is referenced further down in the `main.go` example.
Found it in another repo that contains a minimal Cobra example: https://github.com/dharmeshkakadia/cobra-example/blob/master/cmd/root.go#L41, seems reasonable and does the trick.
=> Add Execute func example in README.md

bash_completions.go, bash_completions_test.go
This PR address the issue reported in #407, the `flaghash` associative array introduced in #205 is only supported on Bash 4, for Bash 3 the attempted assignment to the array results in the error returned in #407. The fix introduced in 801364a only addresses the initial declare.
The fix in this case is to only attempt to assign to the `flaghash` on Bash versions greater than 3.
This PR also updates the names of the functions in the preamble, currently all bash completions generated by cobra have preamble functions with the same name, meaning that only one particular version of a function will be available at any given time - depending on the order in which the completions are sourced.
The fix here is to prefix these functions with the name of the command for which the completion is …
=> Fix generated bash completion for Bash 3 (OSX)

.circleci/config.yml
I wrote a basic config on how to get everything that's currently building right now with CircleCI 2.0. This offers faster, more flexible CI builds. Here's how this compares:
Travis CI builds (master branch)
- longest run/total: 3min 19secs
- all:
- Go v1.76 - 0min 51secs
- Go v1.83 - 0min 54secs
- Go latest - 3min 19secs
CircleCI 1.0 (master branch)
- Go 1.9.1 - 1min 36secs
CircleCI 2.0 (branch of master branch)
- longest run/total: 0min 38secs
- all:
- Go v1.76 - 0min 33secs
- Go v1.83 - 0min 34secs
- Go latest - 0min 14secs
If interested, we could also do test metadata collection, more versions of Go to test with, etc.
Lastly, if there's interest in merging this or not, it might make sense to bump the testing here and/or in `.travis.yml` to test on Go v1.9.x. Especially with Go v1.10 …
=> Enable CircleCI 2.0

bash_completions.go
If one has a program with`cmd.MarkFlagRequired("flagname")` and the user enters:
```
program [tab][tab]
```
The result will be `program --flagname=[[:space:]]` when we really want `program --flagname=` (with no space).  If the user instead did:
```
program -[tab][tab]
```
The result would have been correct.
This checks if there is a single value in COMPREPLY and if so if that value is a flag. If so it will not add the extra space on the end of the completed command line.
=> Do not add a space after a single flag completion

bash_completions.go, bash_completions.md
This is continuation of PR #588 ( i messed up branch during rebasing from master).
I've taken out the code to support "cobra command aliases" which needed to use flaghash. I will work on that as a separate PR.
This current changes are just to support bash aliases for the root command
so we can do like: 
alias aliasname=origname
complete -o default -F __start_origname aliasname
and then we can use aliasname with completions working.
=> Bash completion aliases

bash_completions.go, bash_completions_test.go
Prior to this PR the autocomplete bash functions were being prefixed with the root command name, but references to those functions from subcommands were having the subcommands prefixed instead - causing the function lookups to fail and error out.
As spotted by @janetkuo in kubernetes/kubernetes#60517:
```
kubectl create -f [Tab] failed with the following message: kubectl
create -f __create_handle_filename_extension_flag: command not found
```
in this case the function being invoked should be:
```
__kubectl_handle_filename_extension_flag
```
This PR switches to using `cmd.Root().Name()` in order to use the root rather than subcommand.
=> Prefix bash functions with root command name

bash_completions.md
The current example is not working.
=> Update the bash completion example for kubectl

command.go
Fixes kubernetes/kubernetes#61184
When `--` is found in the command line, the args come after should not be treated as regular flags.
Just like the example shown in kubernetes/kubernetes#61184, the `normalizeNameFunc` should be only applicable for args before `--`.
@eparis @bogem PTAL
=> terminates the flags when -- is found in commandline

command.go, command_test.go
fixes https://github.com/spf13/cobra/issues/623
=> Add support for ignoring parse errors

cobra/cmd/init.go
after doing cobra init pkg/name/command, it prints the abs path with a dot. which is a little annoying to copy
Kindly merge if you think this change is acceptable.
=> remove dot after the abs path

bash_completions.go, bash_completions.md, bash_completions_test.go
- fixes issue where multiple cobra apps using custom bash completion
would have their __custom_func collide
- support fallback to plain __custom_func to maintain compatibility
#694 
I tested this with a cobra app I'm developing locally and had success.  I'm not totally sure how write automated tests for it other than the changes I made.
=> Qualify custom bash func name

README.md
The `swarm` CLI (https://github.com/giantswarm/cli) is no longer maintained, as it's been replaced by `gsctl`.
Cheers
=> Replace Giant Swarm 'swarm' with 'gsctl' in README

README.md
This cleans up a small issue in README.md
=> Remove unneeded imports from README.md example

README.md, args.go, args_test.go
Added a convenience method that combines ValidArgs() and ExactArgs(int)
=> Added ExactValidArgs

.circleci/config.yml, .travis.yml, bash_completions_test.go
The formatting of gofmt changed slightly in go 1.11.  The release notes recommend to use a specific binary of gofmt.  See https://golang.org/doc/go1.11#gofmt
This PR adapts to the new formatting applied by gofmt and changes the configs for travis and circleci to run gofmt only with go 1.11.
=> Run tests against go 1.11 and drop 1.9

bash_completions.go, bash_completions_test.go
Flags like `--namespace` can also be a two-word flag, but the current completion considers only shorthand flags as two-word flags.
I also added test cases for two-word flags.
=> Fix two word flags

cobra.go, command_win.go
New variable `MousetrapDisplayDuration` allows to modify the default display duration of 5s, or to completely disable the timeout and wait for the user to press the return key.
This allows for greater flexibility, instead of having to define a custom `preExecHook` for even such a small change. The requirement arose as in a UAT few users weren't able to read the message within the small default time span of only 5s. IMHO, if you wanted to keep the Mousetrap feature included, it should be configurable at least at a bare minimum.
This PR does not change the default behaviour.
=> added variable to allow configuration of mousetrap message duration

README.md
[gardener/gardenctl](https://github.com/gardener/gardenctl) is the command-line client for [Gardener](https://github.com/gardener/gardener/) - open-source Kubernetes clusters as a service providing support for multiple cloud providers (AWS, GCP, Azure, OpenStack).
=> Add gardenctl to projects build using Cobra

command.go, command_test.go
A couple of issues in the past have already requested the ability of setting stdio (in, out, err): https://github.com/spf13/cobra/issues/763 https://github.com/spf13/cobra/issues/658
In addition, there are some discussions about testing cobra based applications https://github.com/spf13/cobra/issues/770
This PR tries to address this by allowing redirection of I/O at the command level allowing for better unit testing.
```
mockOut := bytes.NewBufferString("")
mockErr := bytes.NewBufferString("")
myCmd.SetIn(mockIn)
myCmd.SetOut(mockOut)
....
err = runMyCmd(myCmd, []string{})
.... 
assert.Equal(t, expectedOut, myCmd.String())
assert.Equal(t, expectedErr, myCmd.String())
```
`stdin` is also considered as some CLI may request data (such as passwords, confirmations) that may also need to be …
=> Extending redirection to stdout, stderr, stdin

bash_completions.go
Fixed shellcheck errors according to documentation:
https://github.com/koalaman/shellcheck/wiki/SC2207
https://github.com/koalaman/shellcheck/wiki/SC2164
**untested** - tests are ok but someone should verify this is correct
=> bash: fix shellcheck errors

README.md, bash_completions.go
This PR adds Linkerd to the list of projects using Cobra.
=> Add Linkerd to list of projects using Cobra

README.md
Someone forgot to initialize cfgFile variable on documentation example which leads to error when doing go get
=> fix undefined cfgFile in documentation

.travis.yml
This PR removes installing shellcheck from caarlos0/shellcheck-docker in the before_install step of Travis jobs.
- The Ubuntu Xenial host in Travis CI includes shellcheck v0.6.0 already (https://docs.travis-ci.com/user/reference/xenial/#compilers-and-build-toolchain).
- The URL is currently wrong (the binary name is `shellcheck_linux`, not `shellcheck`). Hence, we are actually using the version provided by Travis, not the one we download.
- The latest version available in caarlos0/shellcheck-docker is [v0.6.0](https://github.com/caarlos0/shellcheck-docker/releases/latest)
=> clean(travis): remove shellcheck from before_install

cobra/cmd/init.go, cobra/cmd/project.go
Keeps the list sorted and prevents future merge conflicts.
=> Used goimports to fix import order

cobra/cmd/add_test.go, cobra/cmd/init_test.go, cobra/cmd/project.go
In https://github.com/spf13/cobra/commit/984374f5b622efc94388e2872915c2d97404adba a `defer func()` was added after a possible `t.Fatal(err)`. This PR moves it before, to ensure that testproject files are removed after a failure.
=> fix: ensure that testproject is removed even after a failure

README.md
Add Go Report Card badge to README.md
This covers https://github.com/spf13/cobra/issues/940 albeit using a different service.
=> add goreportcard to readme

README.md
The cmd/root.go example in the readme is out of date.  This PR updates the example with what is currently in cmd/root.go.
Resolves https://github.com/spf13/cobra/issues/967
=> Update cmd/root.go example in README.md

doc/man_docs.go, go.mod, go.sum
Pull in the v2 version of md2man, which carries the go.mod compatible version of blackfriday, avoiding broken dependencies for consumers.
Fixes #805
=> Update md2man to v2.0.0

doc/md_docs.md
I noticed that was used 'man' instead of 'Markdown'
=> substitute wrong word in md_docs

command.go
Fixes #1002
For backwards compatibility reasons, and to follow the need of
https://github.com/kubernetes/kubernetes/pull/26077#issuecomment-230818900
the help message should be printed on stdout.
/cc @bruceadowns @bogem @jharshman
=> Revert change so help is printed on stdout again

cobra/cmd/testdata/main.go.golden, cobra/cmd/testdata/root.go.golden, cobra/tpl/main.go
Currently, after templates are generated, `gofmt` has to be run against the files in order to properly format them.
Goal here is to have the output of the templates not need additional formatting to fall in line with Go standard format.
=> Apply formatting to templates

bash_completions.go
PR #889 introduced a small regression where the global variable `$c` is no longer set when `*custom_func` is called.  This is because `$c` is re-used by mistake in the new `read` loop.
This PR simply changes the name of the variable used in the loop.
I've proposed a PR to the `helm/helm` projet which uses the `$c` variable in `__helm_custom_func` and when testing with the `master` branch of Cobra, things started failing.  With this PR applied, the `helm/helm` PR works again.
See https://github.com/helm/helm/pull/7078/files#diff-84d051076d41e254e011a57e40b82a34R279 for the line using `$c` in the PR.
/cc @rsteube @jharshman
=> Fix regression when calling *_custom_func

README.md
The readme example is broken as `er` is undefined.
=> fix: undefined er

command.go, command_test.go
This PR adds support for `context.Context`. It could help people struggling with passing context to the Run functions, that previously had to wrap `cobra.Command` initialization inside another function that would accept context.
So now instead of doing:
```go
func createFooCommand(ctx context.Context) *cobra.Command {
return &cobra.Command{
Use: "foo",
Run: func(cmd *cobra.Command, args []string) {
// Use context here
// ...
}
}
}
```
you would do:
```go
cmd := &cobra.Command{
Use: "foo",
Run: func(cmd *cobra.Command, args []string) {
ctx := cmd.Context()
// Use context here
// ...
}
}
// Get ctx from somewhere else.
cmd.ExecuteContext(ctx)
```
This PR is fully backward-compatible, and doesn't require users to use context at all.
It renders this PR https://github.com/spf13/cobra/pull/727 …
=> Add support for context.Context

command.go, command_test.go
Fixes #654 by adding a `-v` shorthand to the automatically-added `version` flag.
- It will not add the shorthand if another `-v` shorthand is already set
- It will not add the shorthand if another `--version` flag is already set
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
=> Add short version flag -v when not otherwise set

command.go, command_test.go
Issue Reference: https://github.com/spf13/cobra/issues/1056
Bug Introduced: #922 
#922 Introduced a new error type that emitted when a command was not runnable. This caused all commands w/o a run function set to error w/ that message and a status code of 1.
This change reverts the addition of that new error. Similar
functionality can be accomplished by leveraging RunE.
=> Partial Revert of #922

cobra/cmd/golden_test.go, command_test.go
This PR replaced deprecated SetOutput function used in test to make it easier to remove the SetOutput in the future.
=> Replace deprecated SetOutput func with SetOut and SetErr in test

README.md
Circle CI is no longer used. This PR removes the badge from the README.
=> Remove Circle CI badge from readme

.github/labeler.yml, .github/workflows/label.yml
adds labeling actions
when certain parts of the code are modified by a 
PR then the corresponding label is added
=> Add Labeler Actions

.github/workflows/stale.yml
automatically labels stale PRs
=> add support for autolabel stale PR

bash_completions.go, bash_completions.md, command.go, custom_completions.go, custom_completions_test.go
This PR allows programs using Cobra to code their custom completions in **Go** directly inside the program itself.
It is a port to Cobra of the custom completion solution introduced in Helm 3.1 (https://github.com/helm/helm/pull/7323).
It is fully-backwards compatible.
It also allows to use both the new Go custom completions and the existing Bash custom completions at the same time.
The PR **introduces a new hidden sub-command: `__complete`** that is to be called by the auto-completion script. I chose the name with a double underscore prefix to make sure this command will not collide with any command of a program.
Along the lines of the existing `ValidArgs` field, support is added for the **`ValidArgsFunction`** field.  The program can register a function that will provide custom …
=> Custom completions coded in Go (instead of Bash)

bash_completions.go, bash_completions.md, command.go, custom_completions.go, custom_completions_test.go
Rename `BashCompDirectives` to `ShellCompDirectives`
When answering questions in #1070 about Zsh completion, I realized that the naming for the Completion Directives could be improved.  Since those completion directives will be used for different shells, and that these names will be consumed by users, it is more appropriate not to include `bash` in the name.
If this is worth doing, it should be done right away before the old names get locked as a released API.  Assuming it is still ok to make this change.
@jharshman what do you think?
=> API (urgent): Rename BashCompDirectives to ShellCompDirectives

command.go, command_test.go
Addresses https://github.com/spf13/cobra/issues/1071
This removes the `SetOutput` method on `*Command` as it is deprecated and replaces those methods with `SetOut` and `SetErr`. 
I didn't touch any of the `SetOutput` methods on `*FlagSet` as that appears to be apart of the `github.com/spf13/pflag` library. Do we think it's valuable to change that library as well?
If we don't want to entirely remove the function just yet, let me know!
=> Remove/replace SetOutput on Command - deprecated

args.go, bash_completions.go, bash_completions.md, custom_completions.go, custom_completions_test.go, fish_completions.go, fish_completions.md
This is an implementation of Fish completion based on the Custom Go Completions of PR https://github.com/spf13/cobra/pull/1035
The PR takes a different approach to completion.  Instead of coding the entire completion in shell script, it delegates to the Go program the responsibility of determining the completion choices.  This makes it simpler to implement completion support, as Cobra provides all the necessary info to easily determine completions.
It automatically supports custom completions once they have been migrated to the Custom Go Completion method of PR #1035.
And it supports automatically adding the "usage" string for command and flag completions to describe these completions.  This is something bash completion doesn't have.
I haven't yet tried to support the other annotations …
=> Fish completion (including support for Go custom completion)

cobra/cmd/init.go
**- Changes**
- Fixed a typo: changed 'applicaton' to 'application'.
=> Fix typo in cmd/init.go

cobra/README.md
Describes the behavior of custom LICENSE generation using properties in
~/.cobra.yml
Fixes #675
=> Fix cobra command README

cobra/cmd/init.go, cobra/cmd/init_test.go
Created this PR to address current behavior. That is all projects will be initialized within the current directory. I also added tests for other cases where we do not expect projects to be created
for absolute paths and relative paths in GOPATH.
Fixes https://github.com/spf13/cobra/issues/1107
=> Fix cobra init cmd help documentation

bash_completions.go
Fixes #1076 
This PR makes bash completion also provide sub-command names when `ValidArgs` or `ValidArgsFunction` are specified.
Here are details about the completions given:
Cobra's **Bash** completion:
Original (before custom Go completions of PR #1035):
- `ValidArgs` XOR `sub-commands` (which means it gives `ValidArgs` and if there are none, then it gives `sub-commands`)
Current:
- `ValidArgs` XOR `ValidArgsFunction` XOR `sub-commands`
With this PR:
- (`ValidArgs` AND  `sub-commands`) XOR (`ValidArgsFunction` AND `sub-commands`)
For info, Cobra's **Zsh** completion does it yet another way:
- `sub-commands` XOR `ValidArgs`
Which which should align eventually.
=> Make bash completion provide sub-command names even if ValidArgs present

command.go, command_test.go
Fixes #1093
When a command requests to DisableFlagParsing, it should not fail due to a missing required flag. 
In fact, such a check would always fail since flags weren't parsed!
To reproduce the problem, one can use this program:
```
package main
import (
"fmt"
"github.com/spf13/cobra"
)
var rootCmd = &cobra.Command{
Use: "testprog",
Run: func(cmd *cobra.Command, args []string) {
fmt.Println("rootCmd called")
},
}
var childCmd = &cobra.Command{
Use:                "child",
DisableFlagParsing: true,
Run: func(cmd *cobra.Command, args []string) {
fmt.Println("childCmd2 called")
},
}
func main() {
rootCmd.PersistentFlags().Bool("flag", false, "required persistent")
// Setting a persistent flag as a required flag
// breaks sub-commands that set DisableFlagParsing==true …
```
=> Ignore required flags when DisableFlagParsing is true

doc/yaml_docs.go, doc/yaml_docs_test.go
When generating documentation in YAML format, include the "Usage" field.
That is present in the Markdown docs, but not in the YAML ones.
=> YAML documentation contains "Usage"

bash_completions.go, command.go, custom_completions.go, custom_completions_test.go
Supersedes #1065.
Fixes #1000 
This PR does two things:
1) adds completion *of* the `help` command so that
```
<program> [tab][tab]
```
will include `help` in the completion choices.  This is done by the first commit provided by @voithos taken from #1065.
2) adds completion *for* the `help` command using `ValidArgsFunction` so that  
```
<program> help [tab][tab]
```
will show all sub-commands (including `help` since `<program> help help` is a valid command), and
```
<program> help <subCmd1> [tab][tab]
```
will show all sub-commands of `<subCmd1>`.  And so forth down the command tree.
=> Add completion for help command

custom_completions_test.go, fish_completions.go, fish_completions_test.go
Fixes #1121.
This is for programs that may contain a `:` or `-` in their name.
Those characters are not accepted in variables for fish, so it was breaking fish completion.
This PR replaces `-` and `:` with a `_` in the fish completions script.
=> Fish does not accept dash or colon in vars

projects_using_cobra.md
werf is a CI/CD & GitOps tool. Cobra is used in [werf's CLI](https://github.com/werf/werf/blob/master/cmd/werf/main.go).
=> Adding werf to projects using cobra

shell_completions.md, zsh_completions.md
The documentation mistakenly mentions that the user could setup zsh completion by doing:
```
source <(myprogram completion zsh)
```
This has been removed.  It was noticed in #1165.
Also, the documentation to the changes to zsh completion did not include the fact that the `-` prefix is now required to complete flag names (as is done for bash completion).  This was added.  It was noticed in https://github.com/spf13/cobra/pull/899#issuecomment-659392225
=> Improve zsh completion documentation

README.md
Pointing slack badge to our [#cobra slack channel](https://gophers.slack.com/archives/CD3LP1199) in the gophers slack.
=> Add slack badge to point to cobra slack channel

cobra/go.mod
PR #1139 introduced a complexity that will have to be taken into account
as we figure out our release pipeline. This fix pins to cobrav1.0.0 as a
temporary workaround.
fixes #1191
=> bugfix/cli: Temporary fix for go get on cobra cli

doc/cmd_test.go, doc/md_docs.go, doc/md_docs_test.go
This patch modifies the GenMarkdownCustom to skip writing a Synopsis
header with the `cmd.Short` duplicated both before and after the header.
Instead, it only writes the `### Synopsis` header and the paragraph when
a `cmd.Long` has some kind of content in it.
Adds `TestGenMdDocWithNoLongOrSynopsis` as the test case.
Resolves #1194
=> doc: GenMarkdown skip Synopsis on empty long cmd

bash_completions.go, bash_completions_test.go, custom_completions.go, custom_completions_test.go
The current custom completion logic does not complete
subcommands when a local flag is set. This is good unless
TraverseChildren is set to true where local flags
can be set on parent commands.
This commit allows subcommands to be completed only
if TraverseChildren is true.
Closes #1170
Closes #1172
=> Complete subcommands when TraverseChildren is set

custom_completions.go, custom_completions_test.go
If a command/flag description contains a linebreak than the shell completion script will interpret this as new command/flag.
To fix this we should only use the first line from the description in the output.
e.g. `cmd.Flags().String("flag", "", "Description for flag\nlonger description")`
=> Handle linebreaks in custom completions.

projects_using_cobra.md
arduino-cli has been using cobra for [almost a year](https://github.com/arduino/arduino-cli/commit/6a2d8de4f3ff7011f29637eac658b07fcbf8f5b3#diff-37aff102a57d3d7b797f152915a6dc16).
I'm also working in [adding shell completion](https://github.com/arduino/arduino-cli/pull/663) using the latest features of cobra 1.0.0
=> add arduino-cli to projects using cobra

projects_using_cobra.md
Adding Kool Dev (https://github.com/kool-dev/kool) to the list of projects using Cobra.
BTW thanks a lot and keep up the great job everyone here!
=> Adding Kool to list of projects using cobra

zsh_completions.go
The zsh completion script output by cobra is a stub completion function which replaces itself with the actual completion function. This technique enables cobra to define helper functions without splitting the completion script into multiple files.  However, the current implementation forgets to call the actual completion function at the end of the stub function, meaning that completion won't work the first time it's invoked in a shell session. This PR is a fix for this problem.
=> Fix zsh completion not working on the first time in a shell session

fish_completions.go
=> fix: fish output redirection

README.md
I just started using Cobra, and was confused as to why MarkFlagRequired didn't seem to be working. It was because I was using a persistent flag, and called MarkFlagRequired instead of MarkPersistentFlagRequired. I think this change makes this more clear.
=> Add example for making persistent flags required

doc/man_docs.go
This addresses #1049 by changing the format of the generated Markdown input.
=> fix manpage building with new go-md2man

doc/md_docs.go, doc/md_docs_test.go
Reverts spf13/cobra#1270
The public method requiring a new arguments is a breaking change. Reverting back for now.
=> Revert "Add the ability to specify a filePostpender in GenMarkdownTreeCustom"

CONDUCT.md
Establish an understanding between user and maintainer.
Set a goal for releases, security fixes and bug patches.
Closes #1232
=> Cobra User Contract

.travis.yml, go.mod
In accordance with our adopted best practices, the main branch and the
next major release of Cobra will deprecate older and un-maintained
versions of Golang.
fix #1322
=> Deprecate Go < 1.14

.github/workflows/Test.yml, README.md
Travis changed their pricing model. Free resources for open source projects were significantly reduced, and maintainers need to periodically request additional "credits". Since this projects is in spf13's namespace, I guess that only he can see the state of the credits.
In practice, most open source projects are migrating from Travis CI to somewhere else, mostly GitHub Actions.
- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
- https://github.com/python-pillow/Pillow/issues/5028
- https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
Refs: #952 #968 #1044 #1075 #1074 #1143 #1323 #1338
=> ci: add GitHub Actions workflow 'Test'

command.go, completions.go, completions_test.go, shell_completions.md
This PR has Cobra automatically provide a `completion` command at the root level if the program does not provide its own, just like for the `help` command.  This lowers the barrier-to-entry and will make shell completion available to all Cobra users.
With this, a program developer does not need to learn or do anything about completion for users of the program to have access to shell completion for all four shells supported by Cobra.
The change is backwards-compatible, since existing handling for completion has not been changed.  However, when no `completion` command is provided by the program, Cobra will now create a standard one.
Cobra will automatically include a `--no-descriptions` flag for `zsh` and `fish`, to allow users to turn off completion descriptions.
The PR also provides three …
=> Have Cobra create 'completion' command automatically

.github/labeler.yml, .github/workflows/labeler.yml
The github [actions/labeler](https://github.com/actions/labeler) workflow now supports the `pull_request_target` trigger which will enable us to have labels on incoming PRs that originated from forks.
This was originally a permissions issue with action/labeler since they did not support actions being run directly from forks. This was documented [in this issue](https://github.com/actions/labeler/issues/12). This new feature has been documented [here](https://github.com/actions/labeler/blob/main/README.md)
And since this is supported directly by Github, I anticipate this will be a much better collaborator experience vs the periodic-labeler tried in #1112
Closes #1092
Let me know if this needs anything else!
=> Add PR labeler with pull_request_target

bash_completions.go
`split` is from bash_completion's `_init_completion -s`.
=> Bash completion variable leak fixes

.github/workflows/Test.yml
Close #1365
Ref #1360 #1363
The behaviour of modules, get and install changed in golang 1.16: https://blog.golang.org/go116-module-changes. This PR fixes the problem on MSYS2 when trying to install richgo and gox.
=> ci/MSYS2: go install @latest

fish_completions.go
Fixes #1279 
Some programs output extra empty lines at the end of their output, which affects the output of the `__complete` command.
`goreleaser` is such an case:
https://github.com/goreleaser/goreleaser/blob/f35534d9d7cbc2d69fcbd4edb78a5d668357fa60/cmd/root.go#L23
Those lines must be ignored for `fish` shell completion to work.
`zsh` and `bash` are not impacted.
To test this fix use the following commands for the program that follows.
```
$ go build -o testprog testprog.go
$ fish
$ ./testprog completion fish | source
$ ./testprog <TAB>
```
**Test program which adds extra empty lines to the output**:
```
package main
import (
"fmt"
"os"
"github.com/spf13/cobra"
)
var completionNoDesc = false
var completionCmd = &cobra.Command{
Use:   "completion [bashzsh|fish|powershell]",
Short: …
```
=> Fix fish completion for programs that output trailing empty lines

powershell_completions.go
Make sure to filter the returned completions before we check if there are valid completions left.
Fixes #1362
=> powershell completion fix no file comp directive

command.go, command_test.go, completions.go, completions_test.go
=> Pass context to completion

completions.go, completions_test.go
Flag definitions like `-asd` are not handled correctly by
the custom completion logic. They should be treated as
multiple flags. For details refer to #1257.
Fixes #1257
=> Custom completion handle multiple shorhand flags together

completions.go, zsh_completions.go
Fixes #1211
Fixes #1212
This PR improves the zsh completion script to allow it to properly handle `ShellDirectiveCompletionNoSpace` and file completion all the time.  Specifically, there was an issue where when `ValidArgsFunction` would always return completions even if they don't match what the user types, the script would not behave right.  Please refer to #1211 and #1212 for specific details.
So this PR no longer counts the number of completions it receives, but instead relies on the zsh `_describe` function and its return code to handle things cleanly.
=> Fix zsh completion handling of nospace and file completion

fish_completions.go
Fixes #1248
Fixes #1303
Fixes #1214
Fixes #1306
This PR fixes multiple bugs in the fish completion script.
Please ses each issue for details.
=> Fix multiple fish completion issues

cobra/cmd/root.go, cobra/cmd/testdata/root.go.golden, cobra/tpl/main.go, go.mod, go.sum, user_guide.md
Since golang <1.14 were deprecated, `mitchellh/go-homedir` is not required anymore. The built-in `os.UserHomeDir` can be used instead.
=> drop mitchellh/go-homedir (#853)

bash_completions.md, bash_completionsV2.go, command.go, completions.go, completions_test.go, shell_completions.md
With Cobra supporting shell completion for Bash, Zsh, Fish and Powershell, having a uniform experience across all shells is a desirable feature.  With Fish (#1048) , Zsh (#1070) and PowerShell (#1208) sharing the same Go completion logic, their behaviour is strongly aligned.
This PR uses the same Go completion code to power Bash completion.
However, it is important to keep support for legacy bash completion for backwards-compatibility of existing bash custom completions (`cmd.BashCompletionFunction` and `BashCompCustom`) which are being used by many programs out there. ~Therefore this PR also adds support for legacy bash custom completion through Go completions (see more below).~ Therefore this PR introduces a V2 version of bash completion while retaining the current V1 support. …
=> Bash completion V2 with completion descriptions

go.mod, go.sum
This PR fixes a number of CVE and security fixes people have asked for. Viper has been bumped to 1.8.1
Running:
```
go list -json -m all | docker run --rm -i sonatypecommunity/nancy:v1.0.22 sleuth --skip-update-check --no-color  > vulnerabilities.txt
```
gives
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Summary                       ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━┫
┃ Audited Dependencies    ┃ 150 ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━┫
┃ Vulnerable Dependencies ┃ 0   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━┛
```
Closes https://github.com/spf13/cobra/issues/1386
Closes https://github.com/spf13/cobra/issues/1421
=> Bump to viper 1.8.1

bash_completions.go, command.go, completions.go
Some CI system(like istio) will call package of istioctl in parallel, if cobra use `flagCompletionFunctions` as a global var, will generate `fatal error: concurrent map writes`.
So it is better to store those functions to `flagCompletionFunctions` as a map of root command(thread-safe), instead of a global var.
ref #1320 (this PR will not fix it, as we only get thread-safe, but no lock for multi threads)
=> fix RegisterFlagCompletionFunc concurrent map writes error

completions.go, completions_test.go
If the interspersed option is set false and one arg is already set all
following arguments are counted as arg and not parsed as flags. Because
of that we should not offer flag completion. The same applies to arguments
followed after `--`.
Fixes #1307
=> custom comp: do not complete flags after args when interspersed is false

completions.go
zsh is now the default on Mac OS, but the $_fpath version of the installation instructions are likely to put the completion in a strange location that the user might not expect (e.g. an oh-my-zsh plugin's function directory).  So, since Mac OS seems to (as far as I can tell) provide a stable location, this PR recommends using that path instead.
=> Add install instructions for zsh on Mac OS

shell_completions.md
I noticed a couple of minor necessary tweaks for the completion documentation.
@jpmcb it would be nice to include this in the release if you can.
=> Fix documentation

bash_completions.go, command.go, completions.go, completions_test.go, fish_completions.go
The flag completion functions should not be stored in the root cmd.
There is no requirement that the root cmd should be the same when
`RegisterFlagCompletionFunc` was called. Storing the flags there does
not work when you add the the flags to your cmd struct before you add the
cmd to the parent/root cmd. The flags can no longer be found in the rigth
place when the completion command is called and thus the flag completion
does not work.
Also #1423 claims that this would be thread safe but we still have a map
which will fail when accessed concurrently. To truly fix this issue use a
RWMutex.
Fixes #1437
Fixes #1320
=> Fix flag completion

projects_using_cobra.md
👋,
I'm reaching out in behalf of [Meroxa](https://meroxa.com/) as one of its developers. We've been using [Cobra](https://github.com/spf13/cobra) since our first [initial commit](https://github.com/meroxa/cli/commit/a3301a0199df4c77a9cabf1662f7858110d387e5) back from January 2020, and we recently [launched our Platform](https://techcrunch.com/2021/04/13/meroxa-raises-15m-series-a-for-its-real-time-data-platform/) to the public.
We continue considering using Cobra as our CLI framework and are [actively](https://github.com/meroxa/cli/releases) working on it, and it'd be really nice to be featured as one of the projects using Cobra in the wild.
Thank you!
=> Add Meroxa CLI

doc/man_docs_test.go, go.mod, go.sum
full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.0...v2.0.1
- Fix handling multiple definition descriptions
- Fix inline markup causing table cells to split
- Remove escaping tilde character (prevents tildes (`~`) from disappearing).
- Do not escape dash, underscore, and ampersand (prevents ampersands (`&`) from disappearing).
- Ignore unknown HTML tags to prevent noisy warnings
=> go.mod: cpuguy83/go-md2man/v2 v2.0.1

README.md
GitHub shows a ToC for any markdown document (not only the README). Therefore, it's not worth the maintainance burden of keeping the ToC in the README up to date manually. This PR removes it.
=> readme: remove ToC, since it's now shown by GitHub

README.md, cobra/README.md, cobra/cmd/add_test.go, cobra/cmd/init.go, cobra/cmd/init_test.go, cobra/cmd/licenses.go, cobra/cmd/root.go, cobra/cmd/testdata/main.go.golden, cobra/cmd/testdata/root.go.golden, cobra/tpl/main.go, user_guide.md
The `cobra` tool needed some extra updating to make it work seamlessly within the world of Go modules. 
I've dramatically simplified it to just work within a Go module. Now within a module you can just `cobra init` and it works. No paths or module names required. 
I've also made two additional behavioral changes:
1. Viper is no longer included by default. I've heard too much feedback from users that are confused by this and don't know where Cobra ends and Viper begins. Let's simplify that experience. 
2. There is no default license. There's questionable legal ramifications with choosing a license for users without their election. Better to have them take an action to set the license.
=> Module aware generator

user_guide.md
I thought this sentence seemed *off*:
> **Note**, that the variable `author` will not be set to the value from config, when the `--author` flag is not provided by user.
In the [Viper documentation](https://github.com/spf13/viper):
> Viper uses the following precedence order. Each item takes precedence over the item below it:
> * explicit call to Set
> * flag
> * env
> * config
> * key/value store
> * default
One would assume that:
> ...the variable `author` will not be set to the value from config, when the `--author` flag *is* provided by user.
Testing with `cobra init` bears this out:
`cobra init --pkg-name test`
```go
/*
Copyright © 2020 Nickolas Kraus
*/
```
`cobra init --pkg-name test --author Me`
```go
/*
Copyright © 2020 Me
*/
```
=> Small correction in README

cobra/cmd/license_gpl_2.go
This removes "Lesser" from the GPL-2.0 header template, since that header is meant to be referring to GPL-2.0 and not LGPL-2.0.
Fixes #879 
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Remove "Lesser" from header for GPL-2.0 template

cobra/cmd/golden_test.go
Running the tests on windows, when two files do not match, diff shows all the content as changed. This PR tells diff to ignore line endings, so it is easier to find the differences.
=> fix(diff): use arg '--strip-trailing-cr'

args_test.go
This PR adds `expectSuccess`, `getCommand` and other helper functions to `args_test`, in order to reduce the verbosity of the source.
I recommend reviewing the commits one by one.
=> args_test: add helper functions 

args.go, args_test.go, user_guide.md
This may end up being helpful related to issues like #838 or #745...
=> enable composing PositionalArgs

.github/dependabot.yml
Close #907
Dependabot was an external service for keeping dependencies up to date. It was bought by GitHub, and it's now a built-in service which integrates with security updates. See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically.
In April, GitHub announced that the external service (*Dependabot Preview*) is to be shut down in August: https://github.blog/2021-04-29-goodbye-dependabot-preview-hello-dependabot/.
This PR adds a dependabot configuration file for checking go dependencies weekly.
Note that this features does NOT auto-merge. It will open PRs, but maintainers will need to merge them, or bump the dependencies otherwise.
Refs: #1420 #1406 #1404 #1364
=> github: add dependabot configuration file

bash_completions.go
when `set -o nounset` in Bash,
the warnings of unbound variables will break the bash completion.
use `kubectl` as example:
```sh
$ set -o nounset
$ kubectl <Tab>-bash: BASH_COMP_DEBUG_FILE: unbound variable
$
```
the warning break bash completion without any completion result,
and cause my cursor move to the newline.
Use `${variable:-}` substitution in Bash ,
that assign an empty string as default for unbound variables to fix the warnings.
=> fix: unbound variables in bash completion

shell_completions.md
this makes using this snippet easier
=> Update shell_completions.md to have automatically rootcmd

completions.go
did some improvements on the completions docs so they look a bit better if exported as markdown (and still look good on plain text):
- indent the example command lines so they are rendered as code blocks
- removed the $ prefix so they are easier to copy/paste
- standarized the Linux and macOS subsections when present
example: 
- https://nfpm-m71s1p3z3-goreleaser.vercel.app/cmd/nfpm_completion_bash/ (without this patch)
- https://nfpm-nmv190dyc-goreleaser.vercel.app/cmd/nfpm_completion_bash/ (with this patch)
=> fix: improve completions help formatting

completions.go, completions_test.go
The `help` short desc is capitalized so we should follow its lead for consistency.
Also fixes #1458.
=> Completion: Capitalize short desc and remove extra space from long 

bash_completions.go, zsh_completions.go
`subDir` seems to be a typo. It is deep inside `bash_completions.go` used to generate bash completion scripts. I am not sure how to write a test for this.
=> fix: typo in {bash,zsh}_completions.go

bash_completions.go, powershell_completions.go, zsh_completions.go
These templates use 4 spaces for indentation, but some lines used tabs.
=> completions: fix mixed tab/spaces indentation

bash_completionsV2.go
Fixes #1508 
Bash completion V2 adds descriptions to completions.  However, with certain options, the description must be removed.  For example the `menu-complete/menu-complete-backward` bash option will immediately insert on the command-line the first completion returned, therefore we must remove the description to avoid it being added on the command-line also.
Based on the documentation found here
https://www.gnu.org/software/bash/manual/html_node/Commands-For-Completion.html
we remove descriptions for the cases:
- menu-complete
- menu-complete-backward
- insert-completions
=> Support different bash completion options

cobra/cmd/root.go
`cobra completion` outputs invalid output "Using config file:" at the top of the completion script. when ~/.cobra.yaml exists.
=> Fix invalid shell completion when used with ~/.cobra.yaml

completions.go, completions_test.go
Fixes #1507 as requested by @jpmcb
This very simple change adds a user option to allow hiding the default completion command.
So, to tell Cobra to make the default `completion` command *hidden*:
```
rootCmd.CompletionOptions.HiddenDefaultCmd = true
```
It replace #1523 which was more flexible but much more complicated.
=> Provide option to hide default 'completion' cmd

.github/workflows/test.yml, Makefile
This PR is to use golangci-lint-action instead of direct download of it's executable.
It allows also to see the tool's reviews outside of the logs in github.
I also formated and fixed the actual reviews.
Some linters were deprecated, so I used there actual versions
=> chore(ci): use golangci-lint-action

command_test.go, powershell_completions.go
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix some typos (mostly found by codespell)

cobra/tpl/main.go
There was a missing `os` import in the root command generation after https://github.com/spf13/cobra/commit/1beb476da9b46aef65cc176d683f4278cb944085 was merged. This prevented the default boilerplate from being buildable
Closes: https://github.com/spf13/cobra/issues/1556
=> Bug fix: includes `os` package import in root command generation

completions.go, completions_test.go
Fixes #1562
Programs that don't have sub-commands can accept any number of args.
However, when doing shell completion for such programs, within the `__complete` command code this very `__complete` command makes it that the program suddenly has a sub-command, and the call to `Find() -> legacyArgs()` will then return an error if there are more than one argument on the command-line being completed.
To avoid this, we first remove the `__complete` command in such a case so as to get back to having no sub-commands.
A go test has been added.
See #1562 for program to reproduce the issue.
=> Remove __complete cmd for programs without subcmds

cobra/cmd/testdata/main.go.golden, cobra/cmd/testdata/root.go.golden, cobra/cmd/testdata/test.go.golden
Similar to a change last year (https://github.com/spf13/cobra/commit/4384b91fb4f13b1a969bce056c81ef9c128e534a) I believe this is required again this year.
Also I think it should be included in https://github.com/spf13/cobra/issues/1565 the winter 2022 release?
=> Bump license year to 2022 in golden files

README.md
Switching from https://godoc.org/ to https://pkg.go.dev/ as the old one redirects to the new one anyway.
=> Update GoDoc link and badge

cobra/README.md
the command didnt worked
❯ go install github.com/spf13/cobra/cobra
go install: version is required when current directory is not in a module
Try 'go install github.com/spf13/cobra/cobra@latest' to install the latest version
=> Fix install command

.github/labeler.yml
Updates the github actions labeler with the new labeling schema.
Ref: https://github.com/spf13/cobra/issues/1603
=> Updates GitHub actions labeler for new labels

.github/workflows/test.yml
Golang 1.18 was released: https://go.dev/blog/go1.18
This PR updates the CI workflow accordingly.
=> ci: test on Golang 1.18

args_test.go
As suggested by @umarcor, these tests make sure we don't break backwards-compatibility with respect to the current behaviour of `legacyArgs()`.
See #1500 which would break the current behaviour of `legacyArgs()`.
=> Add backwards-compatibility tests for legacyArgs()

completions.go, completions_test.go
Example usage:
choices := []string{"choice1", "choice2", "choice3"}
cmd.RegisterFlagCompletionFunc(cobra.FixedCompletions(choices, ShellCompDirectiveNoFileComp))
=> Introduce FixedCompletions

command.go, command_test.go
Basically the same as https://github.com/spf13/cobra/pull/1517 but uses the `Set<field>` naming convention instead of `WithContext` 
Context setting without execution is important because it means that more design patterns can be achieved.
Currently I am using functional options in a project and I can add behaviour through functional options as such:
```go
type GrptlOption func(*cobra.Command) error
func WithFileDescriptors(descriptors ...protoreflect.FileDescriptor) GrptlOption {
return func(cmd *cobra.Command) error {
err := CommandFromFileDescriptors(cmd, descriptors...)
if err != nil {
return err
}
return nil
}
}
```
I've got a lot more options and this pattern allows me to have nice abstracted pieces of logic that interact with the cobra command. 
This Pattern also allows for adding …
=> Add Command.SetContext

command.go
Closes #1578, together with #1551.
Is an alternative to #1582. Previous discussion on this topic can be found there.
=> Fix Command.Context comment

projects_using_cobra.md
[Kubescape](https://github.com/armosec/kubescape) is a Kubernetes security tool with over 5.4k stars on GitHub. Adding it to the list of projects using cobra
=> Add Kubescape to projects

README.md, user_guide.md
I was going through the ```README.md``` file and noticed at the very end when I clicked on ```The COBRA Generator README``` link, it opened the webpage properly but shows a ```Branch not found, redirected to default branch.``` message every time that kind of feels annoying 🙂 
Have updated the link in the ```README.md``` with the correct branch name as a ```good first issue``` contribution to this repo 🙂
=> Changed branch name in the cobra generator link to 'main'

.github/workflows/test.yml
In order to more easily spot failing tests in GitHub Actions.
=> ci/test: RICHGO_FORCE_COLOR

zsh_completions.go
Without this, slightly older versions of zsh fail to correctly parse the output of the __complete
command. Tested that with zsh 5.0.2 and zsh 5.8. Since this is just correctly quoting the output of
a command, it shouldn't cause any compatibility issues.
=> Wrap printf tab with quotes

projects_using_cobra.md
This PR adds Polygon Edge to the list of projects using Cobra CLI.
We've added support for Cobra a while back:
https://github.com/0xPolygon/polygon-edge/pull/410
=> Add Polygon Edge as a project using Cobra

shell_completions.md
Discovered when copying the code block.
Did not create an issue since change was minor.
=> Minor typo fix in shell_completion.md

bash_completionsV2.go
Using a command substitution, i.e. a subshell, with `printf` is expensive for this purpose. For example `__*_format_comp_descriptions` is run once for each completion candidate; the expense adds up and shows when there are a lot of them.
This shaves off roughly 25% of the times I receive for my test case in #1680 (~2 seconds before, ~1.5 after).
=> perf(bash-v2): use backslash escape string expansion for tab

bash_completionsV2.go
Even though this to my surprise works, it doesn't accomplish anything but some confusion. Remove it.
=> style(bash-v2): out is not an array variable, do not refer to it as such

bash_completionsV2.go
Refactor to remove two loops over the entire list of candidates.
Format descriptions only for completions that are actually going to be displayed, instead of for all candidates.
Format descriptions inline in completions array, removing need for a command substitution/subshell and a printf escape per displayed completion.
These changes shave off a second or so from my case at hand in #1680, it was roughly ~1.7s before, is now ~0.7s after.
The diff is largish, but the bulk of it is in `__%[1]s_format_comp_descriptions` due to indentation changes, there aren't that many lines actually changed in it either. `git show -w` helps with the review.
Caveat: I have not actually tested generating completions with this code. I worked on the improvements by tweaking an existing emitted completion shell …
=> perf(bash-v2): standard completion optimizations

bash_completions.go
For legacy bash completions, similarly as commit 4f0facbcee0aadb87179d3fed80e92709de491a9 is for bash completions v2.
As a side effect, fixes test suite with shellcheck 0.8.0 installed; apparently the 0.7.0 that's in GitHub Actions' ubuntu-latest at the
moment does not flag the array quoting related issue that was provoked from 0.8.0 before this change.
=> style(bash): out is not an array variable, do not refer to it as such

bash_completionsV2.go
If the list of candidates has no descriptions, short circuit all the description processing logic, basically just do a `compgen -W` for the whole list and be done with it.
We could conceivably do some optimizations like this and more when generating the completions with `--no-descriptions` in Go code, by omitting some parts we know won't be needed, or doing some things differently. But doing it this way in bash, the improvements are available also to completions generated with descriptions enabled when they are invoked for completion cases that produce no descriptions. The result after this for descriptionless entries seems fast enough so it seems there's no immediate need to look into doing that.
This alone pretty much eliminates all the slowness related to my specific use case in #1680, …
=> perf(bash-v2): short-circuit descriptionless candidate lists

bash_completionsV2.go
Use simple prefix match instead of single word `compgen -W` command substitution for each candidate match.
It's a bit late, but I can't think of a case where this replacement wouldn't be ok this late at night. Performancewise this improves the cases with descriptions quite a bit, with current https://github.com/marckhouzam/cobra-completion-testing/pull/15 on my box, the v2 numbers look like the following (I've stripped the v1 numbers from each list below).
Before (current master, #1686 not merged yet):
```
Processing 1000 completions took 0.492 seconds which is less than the 1.0 seconds limit
Processing 1000 completions took 0.600 seconds which is less than the 2.0 seconds limit
Processing 1000 completions took 0.455 seconds which is less than the 1.0 seconds limit
Processing 1000 …
```
=> perf(bash-v2): speed up filtering entries with descriptions

bash_completionsV2.go
Similarly as fb8031162c2ffab270774f13c6904bb04cbba5a7 (+ the empty entry fix in https://github.com/spf13/cobra/pull/1691) did for the "regular", non-menu completion cases.
I have no numbers on this, but I'm assuming the speedups seen elsewhere are here too, and didn't notice anything breaking in casual manual tests.
Could be useful to add some perf numbers for the menu-complete code path too to [marckhouzam/cobra-completion-testing](https://github.com/marckhouzam/cobra-completion-testing/) (maybe as well as other tests, haven't checked if there are any).
=> perf(bash-v2): speed up filtering menu-complete descriptions

bash_completions.go, doc/man_docs.go, doc/man_docs_test.go, doc/md_docs.go, doc/rest_docs.go, doc/yaml_docs.go, fish_completions.go
Minor change that gopls pointed out. I think it improves readability a bit.
=> Prefer ReplaceAll instead of Replace(..., -1)

bash_completionsV2.go
`read` gives a last null value following a trailing newline.
Regression from fb8031162c2ffab270774f13c6904bb04cbba5a7.
We could drop the `\n` from the feeding `printf` to accomplish the same end result, but I'm planning to submit some related cleanups a bit later that wouldn't play well with that approach, so I went with explicit filtering here.
=> fix(bash-v2): skip empty completions when filtering descriptions

bash_completionsV2.go
Not that it'd really matter that much performancewise given the level we are at for this case, but this change makes the short circuit roughly twice as fast on my box as it was for the 1000 rounds done in marckhouzam/cobra-completion-testing.
Perhaps more importantly, this makes the code arguably slightly cleaner.
Before:
```
...
<= TIMING => no descriptions: 1000 completions took 0.039 seconds < 0.2 seconds limit
...
<= TIMING => no descriptions: 1000 completions took 0.046 seconds < 0.2 seconds limit
...
```
After:
```
...
<= TIMING => no descriptions: 1000 completions took 0.022 seconds < 0.2 seconds limit
...
<= TIMING => no descriptions: 1000 completions took 0.024 seconds < 0.2 seconds limit
...
```
=> perf(bash-v2): read directly to COMPREPLY on descriptionless short circuit

zsh_completions.go
As reported by @VorpalBlade in https://github.com/twpayne/chezmoi/issues/2047:
Previously the generated zsh completion script started with the line
#compdef _<command> <command>
where \<command\> is the command that the zsh completion script is generated for.
This enabled completions for both \<command> and _\<command>, but _\<command> is the completion function itself and should not be completed. Furthermore, attempting to autocomplete _<command> (e.g. typing "_\<command>\<Space>\<Tab>" in a zsh shell) causes zsh to hang.
This commit fixes the #compdef line to only complete \<command>, not _\<command>.
Co-authored-by: Arvid Norlander <VorpalBlade@users.noreply.github.com>
=> fix: Don't complete _command on zsh

completions.go, shell_completions.md
Using `$(brew --prefix)` is more generic, since the intel version is located in `/usr/local`, but the ARM version is located in `/opt/homebrew`
=> Modify brew prefix path in macOS system

active_help.go, active_help.md, active_help_test.go, bash_completions.go, bash_completionsV2.go, bash_completionsV2_test.go, bash_completions_test.go, command.go, completions.go, fish_completions.go, fish_completions_test.go, power_completions_test.go, powershell_completions.go, user_guide.md, zsh_completions.go, zsh_completions_test.go
This PR is a proposal to enhance the shell completion logic with a framework for what I call "Active Help".
Active Help are messages (hints, warnings, etc) that are printed during the use of the program using the shell completion system.  It aims to help teach how to use the program in an "active" fashion.
For example, 
```
bash-5.1$ helm repo add [tab]
You must choose a name for the repo you are adding
bash-5.1$ bin/helm package [tab]
Please specify the path to the chart to package
bash-5.1$ bin/helm package [tab][tab]
bin/    internal/    scripts/    pkg/     testdata/
```
Active Help messages are defined by the program by adding them as custom completions using `ValidArgsFunction` and `RegisterFlagCompletionFunc` and a new function: `cobra.AppendActiveHelp(completionArray, …
=> Add Active Help support

fish_completions_test.go
Hello :smiley:
Add unit test for untested code sections.
=> Improve fish_completions code quality

bash_completionsV2.go
Fixes #1734
Tab characters that introduce completion descriptions weren't properly being handled with bash v3.  This change fixes that.
This PR fixes the detection of tab characters in the list of completion choices when using bash v3.
See #1734 for details.
Test failures could be seen when running the bash completion tests of https://github.com/marckhouzam/cobra-completion-testing
=> Fix handling of descriptions for bash v3

command.go, user_guide.md
This is a follow-up of #1547. See https://github.com/spf13/cobra/pull/1547#issuecomment-1050245825.
=> undefined or nil Args default to ArbitraryArgs

completions.go, completions_test.go, flag_groups.go
This PR teaches the shell completion logic how to handle the new flag group feature of #1654.
To avoid mucking about in the already complex shell completion logic, I took a different approach.
When we are doing shell completion, we first check flag groups like this:
1. when a flag in a group is present, other flags in the group will be marked required
1. when a flag in a mutually exclusive group is present, other flags in the group will be marked as hidden
Since the completion logic already handles required flags and hidden flags, this approach allows the standard completion logic to automatically behave appropriately for flag groups.
To specific changes are in the last commit of this PR.
@johnSchnake @Luap99
=> Add shell completion to flag groups

projects_using_cobra.md
Reaching out on behalf of KubeVirt, an add-on for Kubernetes, enabling
users to run Virtual Machines on Kubernetes pods.
=> Add KubeVirt as a project using cobra

doc/yaml_docs.go, doc/yaml_docs_test.go
The `see_also` section for child commands would include only the name of command. This adds the whole path, similar to how it's done for the other documentation formats.
=> fix: correct command path in see_also for YAML doc

bash_completionsV2.go
```shell
$ set -u
$ foo=()
$ echo ${#foo}
bash: foo: unbound variable
echo ${#foo[*]}
0
```
=> fix(bash-v2): activeHelp length check syntax

doc/yaml_docs.go, go.mod, go.sum
API v3 was released in 2019 [1]. Update from the v2 API, no changes to
the packages's use needed and no breaking changes expected.
[1] https://ubuntu.com/blog/api-v3-of-the-yaml-package-for-go-is-available
=> Update gopkg.in/yaml.v2 to gopkg.in/yaml.v3

command.go, command_test.go
This fixes a bug where a child flag that shadows (has the same name as) a parent persistent flag would not be shown in the child command's help output and the parent flag would be shown instead under the global flags section.
This change makes the help output consistent with the observed behavior during execution, where the child flag is the one that is actually used.
This change also allows a previously skipped/failing test to be unskipped because it passes now: `TestOverwrittenFlag`
Fixes #1651
=> fix: show flags that shadow parent persistent flag in child help

.github/workflows/test.yml
Golang 1.19 was released: https://go.dev/blog/go1.19
Ref: #1635
=> ci: test on Golang 1.19

command.go
Documentation of Context() was fixed in #1639, especially the fact that the underlying ctx is set to context.Background when Execute() is called (otherwise returns nil). 
The documentation of SetContext() states that the ctx is set to context.Background "by default", which is a bit imprecise (and confused some coworker of mine). I think the Context() method provides the needed information when exactly the context is set to Background. I don't see a need to also document this behavior in the comment of SetContext(), as it is only interesting for a caller of Context().
=> Clarify SetContext documentation

Makefile
When using go 1.18, the format "go install github.com/kyoh86/richgo@latest" is needed (go get no longer works).
This PR simply updates the warning printed by the Makefile to use "go install" instead of "go get".
Note that "go install github.com/kyoh86/richgo@latest" works with go 1.16 and higher but does not work with go 1.15.  However, since installing "richgo" is only required for people who want to run the go tests for the Cobra project itself, I feel it is ok to focus on go 1.16 or higher in this case.
@umarcor you setup richgo, what do you say?
=> With go 1.18, we must use go install for a binary

.github/workflows/stale.yml
Somehow we had the wrong `exempt-` keys in our stale action yaml (or maybe they changed it) causing the stale action to label some `lifecycle/frozen` issues and PR as stale.
This should fix that and make `lifecycle/frozen` labeling do the right thing
=> Use correct stale action `exempt-*` yaml keys

args.go, args_test.go, user_guide.md
This is a subset of #841, which was approved by @jharshman and reviewed by @marckhouzam .
Fix #838 and Fix #745.
The original validators care about the number of arguments that a command accepts: `NoArgs`, `ArbitraryArgs`, `MinimumNArgs(int)`, `MaximumNArgs(int)`, `ExactArgs(int)`, `RangeArgs(min, max)`. We can consider it an enumeration of 6 items.
When `ValidArgs` was introduced, up to six additional validators might have been added, in order to provide functions covering the full combination matrix. Certainly, `ValidArgs` is a boolean condition which is orthogonal to `Args`, because it is focused on the content of the args, not the number of them. Therefore, the full matrix covers 6 x 2 = 12 combinations. However, `NoArgs` + `ValidArgs` == `NoArgs` + `!ValidArgs`, so 11.
Nonetheless, …
=> deprecate ExactValidArgs and test combinations of args validators

cobra.go, command.go, command_test.go
Add a global `EnableCaseInsensitive` variable to allow
case-insensitive command names.
The variable supports commands names and aliases globally.
Resolves #1382
=> Support for case-insensitive command names

.github/workflows/test.yml
Since v3, Action setup-go has built-in support for caching modules. See https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs.
Ref: #1660
=> ci: use action/setup-go's cache

.github/workflows/test.yml
The workflow dispatch event allows maintainers or forkers to trigger CI runs either through the web GUI or through the API. See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch.
=> ci: add workflow_dispatch

shell_completions.md
When adding the option to hide the default `completion` command in #1541, I forgot to document it!
This PR simply adds that option to the documentation.
=> Document option to hide the default completion cmd

command.go, flag_groups.go
Hi, dear reviewers,
In my project, there is one complex command with a lot of flags, we need to set part of them as required, and other flags are optional, all optional flags were defined from an API server. I have implemented this feature to add dynamic flags in issue #1758.
as talked with @marckhouzam in the last issue, it looks like my method is on the right way.
In the next work, I add some flags in `init()` function and call `MarkFlagRequired` to mark them as required flags. but, because I have set `DisableFlagParsing` as `true`, and need to call `func (c *Command) ParseFlags(args []string) error` to parse all flags manually, the function which validates the required flag will not be called. 
for now, I have to set up a map and store all required flags, then check if exist in …
=> expose ValidateRequiredFlags and ValidateFlagGroups

cobra.go, command.go
This method is the OnInitialize counterpart. Like OnInitialize which allows loading the configuration before each command is executed, OnFinalize allows saving the configuration after each command has been executed.
=> Add OnFinalize method

.github/workflows/labeler.yml, .github/workflows/size-labeler.yml, .github/workflows/stale.yml, .github/workflows/test.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
Here is an example of the permissions in one of the workflows:
https://github.com/spf13/cobra/runs/8125223301?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_t …
=> ci: add minimum GitHub token permissions for workflows

powershell_completions.go, shell_completions.md
I ran across a possible problem with using powershell completion with aliases.  I can't recall where it was though, but the situation is pretty simple.
IIUC, when a user has an alias in powershell, she needs to register that alias for completion using:
```
PS> Register-ArgumentCompleter -CommandName 'aliasname' -ScriptBlock <completionBlock>
```
The problem is that the `<completionBlock>` is currently not accessible in our powershell script.
To address this, this commit stores the completion logic into a scriptblock variable which can easily be accessed by the
user to register aliases.
For example, if the user defines an alias for `helm` she will be able to register an alias like this:
```
PS> sal h helm
PS> Register-ArgumentCompleter -CommandName 'h' -ScriptBlock $__helmCompleterBlock …
```
=> Allow user to add completion for powershell alias

command.go, completions.go, completions_test.go
Fixes #1786
Thanks to @fnickels's nice work on #1707, I realized why the `--help`/`-h` and `--version`/`-v` flags where not included in shell completions.
The `--help`, `-h`, `--version` and `-v` flags are normally added when the `execute()` function is called on a command.  When doing completion we don't call `execute()` so we need to add these flags explicitly to the command being completed.
Also, when doing shell completion following those flags, this PR disables all completions.
To do so, we keep track of if the `--help` and `--version` flags were added by Cobra using a new flag annotation.
To test:
```
./prog -<TAB>
./prog --help <TAB>
```
=> Include --help and --version flag in completion

README.md, command.go, command_test.go, completions.go, user_guide.md
Adds the possibility to group the commands in the help message.
closes #836 
closes #1271
=> Add groups for commands in help

shell_completions.md, user_guide.md
Update the example from `shell_completions` by replacing `ExactValidArgs` which is deprecated from the documentation by `MatchAll(ExactArgs(1), OnlyValidArgs)`.
=> Replace deprecated ExactValidArgs with MatchAll in user_guide and shell_completions example

command.go, command_test.go, user_guide.md
Fixes #1831
Replaces #1835
By moving the check for help group existence to "ExecuteC()" we no longer need groups to be added before AddCommand() is called.  This provides more flexibility to developers and works better with the use of "init()" for command creation.
cc @aawsome
=> Check for group presence after full initialization

command.go, command_test.go, user_guide.md
```
Fixes #1831
By moving the check for help group existence to "ExecuteC()" we no longer need groups to be added before AddCommand() is called.  This provides more flexibility to developers and works better with the use of "init()" for command creation.
Signed-off-by: Marc Khouzam <marc.khouzam@gmail.com>
```
=> 🍒 Cherry-pick `v1.6.x` - Check for group presence after full initialization (#1839)

command.go, command_test.go
When the command searches args to find the arg matching a particular subcommand name, it needs to ignore flag values, as it is possible that the value for a flag might match the name of the sub command.
This change improves argsMinusFirstX() to ignore flag values when it searches for the X to exclude from the result.
Fixes #1777
=> fix: don't remove flag value that matches subcommand name

command_test.go
Created a unit test that tests the unknown flag error message when the unknown flag is located in different arg positions.
I think this bug (the first test case with the `FIXME` comment) has been around for a long time, and I decided to create a test to demonstrate it.
I haven't really looked into how this might be fixed yet, just thought I would start with a test first.
=> Create unit test illustrating unknown flag bug

.github/workflows/test.yml, Makefile
Reduce the barrier to entry by making makefile target `test` use `go test` and adding target `richtest` to be used in CI.
=> Makefile: add target richtest

projects_using_cobra.md
Signed-off-by: David Wertenteil <dwertent@armosec.io>
The Kubscape project has been moved from the [armosec](https://github.com/armosec) org to the [kubescape](https://github.com/kubescape) org.
=> docs: update kubescape org

cobra.go
`template` is an import in `cobra.go` file and also used as a variable name, which masks the library in the scope of that function.
=> fix: conflict import name with variable

args.go, bash_completions.go, command.go, completions.go, doc/rest_docs.go
Corrected the function name at the start of doc strings, as per the convention
outlined in official go documentation: https://go.dev/blog/godoc
Though a minor change, but found this while browsing through the code.
=> fix: func name in doc strings

command.go, completions_test.go
Previously, arguments with a dash as the second character (e.g., 1-ff00:0:1) were detected as a flag by mistake.
This resulted in auto completion misbehaving if such an argument was last in the argument list during invocation.
Fixes #1816
=> completions: do not detect arguments with dash as 2nd char as flag

shell_completions.md
=> add a hint about the disabling completion descriptions to document

bash_completions.go, bash_completionsV2.go, completions.go, fish_completions.go, powershell_completions.go, shell_completions.md, zsh_completions.go
=> added keep order to bash, zsh, pwsh & fish

powershell_completions.go
PowerShell 7.2 has changed the way arguments are passed to executables. This was originally an experimental feature in 7.2, but as of 7.3 it is built-in. A simple "" is now sufficient for passing empty arguments, no back-tick escaping is required.
Fixes #1849
=> Add support for PowerShell 7.2+

.github/workflows/test.yml
As #1866, this PR removes go 1.16 from CI (since it's failing due to a test dependency) but keeps the `go.mod` unmodified.
=> ci: deprecate go 1.16

.github/workflows/test.yml
Golang 1.20 was released a month ago: https://go.dev/blog/go1.20
Ref: #1782
=> ci: test Golang 1.20

projects_using_cobra.md
This Pull Request updates the `projects_using_cobra.md` file to add Vitess and Arewefastyet as projects that are using Cobra.
=> Update `projects_using_cobra.md` add `Vitess` and `Arewefastyet`

user_guide.md
Document the approach suggested in https://github.com/spf13/cobra/issues/266#issuecomment-817295792.
=> Document suggested layout for subcommands

completions.go, zsh_completions.go
Although it is not the recommended approach, sourcing a completion script is the simplest way to get people to try using shell completion. Not allowing it for zsh has turned out to complicate shell completion adoption.  
Also, it has caused multiple issues to be opened on the Cobra project because people could not get zsh completion to work.  One can look for the string `compdef` in: #881 #986 #887 #1264 #1325 #1796
Further, many tools modify the zsh script provided by Cobra to allow sourcing, which kind of makes Cobra's stance, not that useful anyway.
This commit allows sourcing of the zsh completion script.
Note that putting the script on `$fpath` continues to be recommended approach and continues to function as before.
=> Allow sourcing zsh completion script

fish_completions.go
This is a trivial fix. The typo broke CI for projects that run a spellchecker (e.g. https://github.com/reviewdog/action-misspell) on their committed code ([like this one](https://github.com/twpayne/chezmoi/actions/runs/4617766534/jobs/8164413060)).
=> Fix typo in fish completions

bash_completions.go, bash_completionsV2.go, cobra.go
The use in generated bash completion files is getting flagged by Lintian (the Debian package linting tool).
=> Fix grammar: 'allows to'

fish_completions_test.go
Use temporary files instead of assuming the current directory is writable. Also, if creating a temporary file still returns an error, prevent the test from failing silently by replacing `log.Fatal` with `t.Fatal`.
=> test: make fish_completions_test more robust

powershell_completions.go, powershell_completions_test.go
This fixes an issue with program names that include a dot, in our case `podman.exe`. This was caused by the change in commit 6ba7ebbc.
Fixes #1853
=> powershell: escape variable with curly brackets

.golangci.yml
Minimal changes to the golangci configuration, to get rid of the following warnings:
```
level=warning msg="[runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
level=warning msg="[runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
level=warning msg="[runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
```
=> golangci: enable 'unused' and disable deprecated replaced by it

command.go
This PR fixes the currently failing job in CI.
/cc @marckhouzam
=> command: temporarily disable G602 due to securego/gosec#1005

.github/workflows/test.yml
Golang 1.21 was released: https://go.dev/blog/go1.21
=> ci: test golang 1.21

command.go, command_test.go, site/content/user_guide.md
You can change the prefix before the error message by `SetErrPrefix()`.
It's currently `Error:`, and now it's read from `errPrefix`.
It's just like the `versionTemplate` and `SetVersionTemplate()` relationship.
Resolve: #1281
=> Customizable error message prefix

completions.go
Would provide a way for reading flagCompletionFunctions map
https://github.com/spf13/cobra/issues/1942
=> feat: add getters for flag completions

cobra.go, command.go, command_test.go, site/content/user_guide.md
Currently, only one of the persistent pre-runs and post-runs is executed.
It is always the first one found in the parents chain, starting at this command.
Expected behavior is to execute all parents' persistent pre-runs and post-runs.
Dependent projects implemented various workarounds for this:
- manually building persistent hook chains (in every hook).
- applying some kind of monkey-patching on top of Cobra.
This change eliminates the necessity for such workarounds
by allowing to set a global variable EnableTraverseRunHooks.
Tickets:
- https://github.com/spf13/cobra/issues/216
- https://github.com/spf13/cobra/issues/252
- https://github.com/spf13/cobra/issues/1198
Signed-off-by: Volodymyr Khoroz <volodymyr.khoroz@foundries.io>
=> Feature: allow running persistent run hooks of all parents

command.go, doc/md_docs.go
When using golangci-lint v1.55.0 some new errors were being reported.
```
command.go:1440:16: string `  -` has 4 occurrences, make it a constant (goconst)
c.Println("  -"+f.Shorthand+",", "--"+f.Name, "["+f.DefValue+"]", "", f.Value, "  [LP]")
^
doc/md_docs.go:86:20: string `.md` has 3 occurrences, make it a constant (goconst)
link := pname + ".md"
^
```
=> Fix linter errors

completions.go, completions_test.go
Fixes #2060
When a command sets `DisableFlagParsing = true` it requests the responsibility of doing all the flag parsing. Therefore even the `--help/-f/--version/-v` flags should not be automatically completed by Cobra in such a case.
Without this change the `--help/-h/--version/-v` flags can end up being completed twice for plugins: one time from cobra and one time from the plugin (which has set `DisableFlagParsing = true`).
=> Don't complete --help flag when flag parsing disabled

completions_test.go
Different problems have been reported about flag completion registration. 
These two tests are the cases that were not being verified but had been mentioned as problematic.
The test `TestFlagCompletionConcurrentRegistration` reproduces the `"concurrent map writes"` errors if concurrency is not properly handed, as reported by #1320.
I have verified this test does fail by running it on code before the fix from #1438.
The test `TestFlagCompletionForPersistentFlagsCalledFromSubCmd` makes sure persistent flags get completed.
This is based on problems mentions here:
- https://github.com/spf13/cobra/pull/1438#issuecomment-872928669
- https://github.com/spf13/cobra/pull/2012#pullrequestreview-1627336420
I have verified this test does fail based on the interim commit that was reported to have this …
=> Add tests for flag completion registration

active_help.go, site/content/active_help.md
There are other characters besides the dash that are fine in program names, but are problematic in environment variable names. These include (but are not limited to) period, space, and non-ASCII letters. (Ok, I see space isn't a "problem" here because how `.Name()` derives from `.Use`.)
Even though the commentary says the format should not change, I think this change is fine, because env vars affected by this are highly unlikely to exist in the wild. This is mostly a "for completeness" change.
=> Replace all non-alphanumerics in active help env var program prefix

command.go, command_test.go
In this case the executable is `kubectl-plugin`, but we run it as:
kubectl plugin
And the help text should reflect the actual usage of the command.
To create a plugin, add the cobra.CommandDisplayNameAnnotation:
rootCmd := &cobra.Command{
Use: "plugin",
Annotations: map[string]string{
cobra.CommandDisplayNameAnnotation: "kubectl plugin",
}
}
Internally this change modifies CommandPath() for the root command to
return the command display name instead of the command name. This is
used for error messages, help text generation, and completions.
CommandPath() is expected to have spaces and code using it already
handle spaces (e.g replacing with _), so hopefully this does not break
anything.
Issues:
- Need documentation
Fixes: #2017
=> Support usage as plugin for tools like kubectl

args.go, bash_completions.go, cobra.go, command.go, completions.go, flag_groups.go
Noticed while looking into something else. No benchmarks/numbers done, but even if this wouldn't yield measurable improvements, the changes don't hurt readability IMO and actually in a sense they convey the intent better.
=> Micro-optimizations

active_help.go, completions.go, completions_test.go, site/content/completions/_index.md
Closes https://github.com/spf13/cobra/issues/1937
=> Add env variable to suppress completion descriptions on create

command.go, command_test.go, site/content/user_guide.md
Using the new CommandDisplayNameAnnotation annotation introduced in Cobra 1.8.0.
Fixes help text issues with:
- help flag usage
- help command long description
- usage line for command without sub commands
=> Fixes and docs for usage as plugin

cobra_test.go
Add test for:
- rpad(s string, padding int) string
- ld(s, t string, ignoreCase bool) int
- stringInSlice(a string, list []string) bool
in cobra.go
=> Add test for func in cobra.go

site/content/projects_using_cobra.md
I'd like to add Taikun to the list o CLIs that use the Cobra framework.
The ClI repo is opensource and can be found [here](https://github.com/itera-io/taikun-cli)
Thanks.
=> Add Taikun CLI to list of projects

.github/workflows/test.yml
Golang 1.22 was released: https://go.dev/blog/go1.22
Any plans for a release soon?
=> ci: test golang 1.22

command_test.go
Replaces deprecated `ioutils.ReadAll` and `io/ioutils` package references
- Closes #2119
=> fix: remove deprecated io/ioutils package

site/content/user_guide.md
Read through the document and refine the details ...
=> docs: update user guide

flag_groups.go
Add `Annotation` suffix to the private annotations to allow nicer code using the constants.
For example one can use the current annotation names as a temporary variable instead of unclear shortcut. Instead of this:
rag := flagsFromAnnotation(c, f, requiredAsGroup)
me := flagsFromAnnotation(c, f, mutuallyExclusive)
or := flagsFromAnnotation(c, f, oneRequired)
We can use now:
requiredAsGrop := flagsFromAnnotation(c, f, requiredAsGroupAnnotation)
mutuallyExclusive := flagsFromAnnotation(c, f, mutuallyExclusiveAnnotation)
oneRequired := flagsFromAnnotation(c, f, oneRequiredAnnotation)
Example taken from #2105.
=> Consistent annotation names

.golangci.yml, command.go, completions.go
"interfaces", "maligned", and "golint" do not produce any report and cause golangci-lint to fail as we can see in the CI.
- Remove "interfaces" and "maligned" linters that have no replacement.
- Replace golint with stylecheck
=> Remove fully inactivated linters

.golangci.yml, command.go
See individual commit messages for details.
=> Address golangci-lint deprecation warnings, enable some more linters

command.go
Deprecation comments should be at the start of a paragraph [1], and because of that have a whitespace above them [2];
> To signal that an identifier should not be used, add a paragraph to its
> doc comment that begins with Deprecated: followed by some information
> about the deprecation (...)
With the whitespace missing, some tools, including pkg.go.dev [3] don't detect it to be deprecated.
[1]: https://go.dev/wiki/Deprecated
[2]: https://go.dev/doc/comment#paragraphs
[3]: https://pkg.go.dev/github.com/spf13/cobra@v1.8.1#Command.SetOutput
Before this patch:
With this patch:
=> Fix deprecation comment for Command.SetOutput

completions.go
Cobra currently allows Slice and Array flags to be completed multiple times, but it doesn't support multiple map flags like `stringToString` and `stringToInt` in the same way.
This PR adds support for map flags to be set multiple times.
=> fix(completions): Complete map flags multiple times

doc/man_docs_test.go, doc/md_docs_test.go, doc/rest_docs_test.go, doc/yaml_docs_test.go, site/content/docgen/md.md, site/content/docgen/rest.md, site/content/docgen/yaml.md
Fixing golangci-lint errors[1]:
Error: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of
Go 1.16, the same functionality is now provided by package [io] or
package [os], and those implementations should be preferred in new
code. See the specific function documentation for details.
(staticcheck)
[1] https://github.com/spf13/cobra/actions/runs/10535452454/job/29194442289?pr=2180
=> Replace deprecated ioutil usage

command.go, command_test.go
When writing a plugin and setting CommandDisplayNameAnnotation you want the display name to be used in help text. This did not work when setting command Version since the help text and version templates used the command Name().
This change makes command DisplayName() public, so it can be used in templates or other code that want to use this value, and fix --version help text and template to use the command DisplayName().
=> Fix --version help and output for plugins

powershell_completions.go
Currently the Powershell completion script generated by Cobra does not work in [constrained mode](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-5.1#constrainedlanguage-mode) because creating CompletionResult Objects is blocked there.
This adds a check to the script that returns results as plain strings if constrained mode is enabled. Results in FullLanguage mode are unchanged.
So far I've tested with Powershell 5.1 on Windows 10, all three completion modes seem to work as expected even in constrained mode.
=> Make Powershell completion work in constrained mode

site/content/active_help.md
Small change to fix a couple of broken links in active_help.md
=> Fix broken links in active_help.md

doc/man_docs_test.go, go.mod, go.sum
Since cpuguy83/go-md2man 2.0.5 no paraTag is written after "SEE ALSO".
With go-md2man 2.0.4:
~~~
.SH SEE ALSO
.PP
\fBroot-bbb(1)\fP, \fBroot-ccc(1)\fP
~~~
With go-md2man 2.0.5:
~~~
.SH SEE ALSO
\fBroot-bbb(1)\fP, \fBroot-ccc(1)\fP
~~~
See: https://github.com/cpuguy83/go-md2man/pull/122
=> Update to latest go-md2man

go.mod, go.sum
fix compatibility with go versions before go1.17 which was broken by #2201 
diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.5...v2.0.6
=> build(deps): bump github.com/cpuguy83/go-md2man/v2 from 2.0.5 to 2.0.6

command.go, command_go120.go, command_go121.go, command_test.go
- relates to https://github.com/spf13/cobra/pull/155
- relates to https://github.com/docker/cli/pull/5224
When running tests in verbose mode (or other options), tests involving Cobra may fail if the test does not explicitly set Command.args to an empty slice; in this case, Cobra defaults to using `os.Args`, which will contain arguments passed to the test (such as `-v` (verbose)).
Commits e5762054c9a6429fa7c234897707d and 1ef0913976db2004980575ed815c3 implemented a workaround for this when running (unit) tests for Cobra itself, but this check is specifig to Cobra (checking for `cobra.test`), and don't work on Windows (which will have a `.exe` extension),
This patch implements a more universal check, so that users of Cobra as a module also benefit from this workaround.
go1.21 and up …
=> Make detection for test-binary more universal

completions.go, completions_test.go
The completion code attempts to detect whether a flag can be specified more than once, and therefore should provide completion even if already set.
Currently, this code depends on conventions used in the pflag package, which uses an "Array" or "Slice" suffix or for some types a "stringTo" prefix.
Cobra allows custom value types to be used, which may not use the same convention for naming, and therefore currently aren't detected to allow multiple values.
The pflag module defines a [SliceValue] interface, which is implemented by the Slice and Array value types it provides (unfortunately, it's not currently implemented by the "stringTo" values).
This patch adds a reduced interface based on the [SliceValue] interface mentioned above to allow detecting Value-types that accept multiple values. …
=> completion: improve detection for flags that accept multiple values

command.go, completions.go
Also document that NoFilesCompletion and FixedCompletion can be used with RegisterFlagCompletionFunc.
=> feat: add CompletionFunc type to help with completions

bash_completionsV2.go
This PR would escape bash v2 completions when there are only one completion left and use line-break to separate completions when passing them to `compgen`. This should fix issues described in #1740 and only affect completions with special characters, such as whitespace.
=> Add similar whitespace escape logic to bash v2 completions than in other completions

cobra.go, cobra_test.go, command.go, command_test.go, completions.go, site/content/user_guide.md
Fixes #2015 
Cobra, in its default configuration, will execute a template to generate help, usage and version outputs. Text/template execution calls MethodByName and MethodByName disables dead code elimination in the Go linker, therefore all programs that make use of cobra will be linked with dead code elimination disabled, even if they end up replacing the default usage, help and version formatters with a custom function and no actual text/template evaluations are ever made at runtime.
Dead code elimination in the linker helps reduce disk space and memory utilization of programs. For example, for the simple example program used by TestDeadcodeElimination 40% of the final executable size is dead code. For a more realistic example, 12% of the size of Delve's executable is deadcode.
This PR …
=> Allow linker to perform deadcode elimination for program using Cobra

bash_completionsV2.go
In the bash shell we used to print ActiveHelp messages on every tab-press. In the example below, notice the `Command help` line which is ActiveHelp:
```
bash-5.1$ tanzu context u[tab]
Command help: Configure and manage contexts for the Tanzu CLI
bash-5.1$ tanzu context u[tab]
Command help: Configure and manage contexts for the Tanzu CLI
bash-5.1$ tanzu context u
unset  (Unset the active context so that it is not used by default.)
use    (Set the context to be used by default)
bash-5.1$ tanzu context u
```
Above, on the first [tab] press, only the ActiveHelp is printed. On the second [tab] press, the ActiveHelp is printed again, followed by a re-print of the command-line, followed by the completions choices.
The separation between ActiveHelp and completion choices makes the ActiveHelp …
=> Print ActiveHelp for bash along other completions

bash_completionsV2.go
Happens at least if a flag is marked as filename, with "" given as extensions.
Foe example, current goreleaser (2.6.1) gives this
```shellsession
$ set -o nounset
$ goreleaser build --output <TAB>bash: fullFilter: unbound variable
```
https://github.com/goreleaser/goreleaser/blob/fb003f17c26e9388be64eb3930fe1b337325cf8d/cmd/build.go#L100
Arguably a bug to set an empty string there. Not sure if this should be filtered before it enters bash code, but at least this is a "cheap" workaround.
=> fix(bash): nounset unbound file filter variable on empty extension

command.go, command_test.go
Follow-up to #1956.
This commit allows a program to reset any of the three templates to their default behaviour, as it was possible to do before the change of #1956.
For example, one could imagine that a program could call `SetUsageTemplate("{{A short help}}")`, but if a particular set of arguments is passed in by the user, the program would want to reset to the default help by calling `SetUsageTemplate("")` (basically cancelling the previous call to `SetUsageTemplate()`).
This used to be possible before #1956, and this PR brings back this support.
Granted, this is a bit of a corner case, but with so many programs using Cobra, let's not make any assumptions and avoid unexpected changes. 
cc @aarzilli @jpmcb
=> Allow to reset the templates to the default

site/content/projects_using_cobra.md
Hi! 
We recently added a CLI to a our Conduit project, and we use Cobra to power it.
Here's a blog post mentioning it https://meroxa.com/blog/introducing-the-new-conduit-cli:-a-powerful-tool-for-managing-your-pipelines/
Thanks!
=> doc: add Conduit

active_help.go, command.go, completions.go, completions_test.go, site/content/active_help.md, site/content/completions/_index.md
The code has also been refactored to use a type alias for completion and a completion helper
Using a type alias is a non-breaking change, and it makes the code more readable and easier to understand.
Fixes #2222
=> feat: add CompletionWithDesc helper

command.go, completions.go, completions_test.go, site/content/completions/_index.md
This supersedes #1450 and #1392
When a program has no sub-commands, its root command can accept arguments.  If we add the default "completion" command to such programs they will now have a sub-command and will no longer accept arguments.
What we do instead for this special case, is only add the "completion" command if it is being called.
We want to have the "completion" command for such programs because it will allow the completion of flags and of arguments (if provided by the program).
@scop can you confirm this is what you were hoping for?
**Testing done**
```
$ cat tests/minimal.go
package main
import (
"fmt"
"github.com/spf13/cobra"
)
var rootCmd = &cobra.Command{
Use: "prog",
Run: func(cmd *cobra.Command, args []string) {
fmt.Println("value:", value)
fmt.Println("args:", args)
},
} …
```
=> Add default completion command even if there are no other sub-commands

go.mod, go.sum
Quick dependency upgrades in preparation of v1.9.0 - cc @marckhouzam - used:
```
go get -u ./...
```
to pull the latest for us to consume: doesn't look like much, just `pflag`
=> chore: Upgrade dependencies for v1.9.0

completions.go, completions_test.go
- **chore: add missing non-regression test for completions**
- **fix: completion helper retro-compatibility**
This PR is about this
- Fixes code implemented in https://github.com/spf13/cobra/pull/2220
- discussion that occurred here https://github.com/spf13/cobra/pull/2231#issuecomment-2661510587
- breaking changes reported here: https://github.com/docker/cli/pull/5827
- possible fix tried on docker-cli: https://github.com/docker/cli/issues/5828
=> fix CompletionFunc implementation

command.go, command_test.go
Fixes https://github.com/spf13/cobra/issues/2240
=> Flow context to command in SetHelpFunc

SECURITY.md
Closes #1658 
Maintainers and community: please review this policy and let us know if there's something missing!
cc @marckhouzam @spf13
=> feat: Add security policy

completions.go, completions_test.go, site/content/completions/_index.md
Closes #2209, #2221 
#2221 proposed a solution where the custom `DefaultShellCompDirective` only applied to a given command.
In https://github.com/spf13/cobra/pull/2221#discussion_r1923845125, alternative approaches were discussed.
We agreed on a recursive solution, where a change applies to a command and its subcommands.
To ease review, I open a new PR for this approach.
=> The default ShellCompDirective can be customized for a command and its subcommands

command.go, go.mod, go.sum
In pflag, we recently made a breaking change in naming to be more inclusive. This change, while doing nothing to address the same uninclusive naming in cobra itself, adjusts to those changes to ensure automatic bumps (if you do them) can continue uninterrupted.
=> Bump pflag to 1.0.8
